### ISSUE TITLE
read.table() incorrectly converts character fields that begin with numbers to numeric vector

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#102]
If you call read.csv() on a text file such as:

```
_id,operation,orderOpenPrice,orderClosePrice,orderOpenTime,orderCloseTime,orderProfit,orderSwap,symbol,orderTicket,volume,status
3909D56A13834DBDAA7A5F637A48B441,OP_SELL,1.13427,1.1373,2015-02-17T08:30:00Z,2015-02-17T09:08:57Z,-151.5,0,EURUSD,122570932,0.5,CLOSED
3151D4C10A17440584D1363747F933B2,OP_BUY,1.13866,1.13834,2015-02-17T09:30:00Z,2015-02-17T15:20:24Z,-16,0,EURUSD,122575039,0.5,CLOSED
A01F4909C00542BD919602F6922DCC0C,OP_SELL,1.13983,1.14088,2015-02-18T02:00:03Z,2015-02-18T03:00:00Z,-52.5,0,EURUSD,122629206,0.5,CLOSED
993E4E765C5947519D89B8C9068346AF,OP_BUY,1.14088,1.13923,2015-02-18T03:00:01Z,2015-02-18T07:30:00Z,-82.5,0,EURUSD,122631062,0.5,CLOSED
235122AAA820439EAE043CA3DD8BF0DF,OP_SELL,1.13923,1.13977,2015-02-18T07:30:00Z,2015-02-18T19:00:49Z,-27,0,EURUSD,122637014,0.5,CLOSED
```

`NumericLiterals.parseDouble()` is called to detect whether the column can be parsed as a number. However, the `parseDouble()` function actually is quite lenient in what it will accept, parsing as much of a string as can be legally converted to a number. 

So `parseDouble("2015-02-17T08:30:00Z,2015-02-17T09:08:57Z")` returns `2015` and `read.csv` converts the column to `c(2015L, 2015L, 2015L...)`

The workaround for this bug is to provide an explicit `colClasses` argument to `read.csv`

**Comment by akbertram** [comment]
@psolaimani can you check to see if this is still the case?

**Comment by psolaimani** [comment]
@akbertram is still the same.

**Comment by akbertram** [comment]
@Artjom-Metro you may have fixed this as well?

**Comment by Artjom-Metro** [comment]
Yes, it actually does:

![image](https://cloud.githubusercontent.com/assets/5359014/18814664/b3d278a8-831a-11e6-9d23-abe9762e64aa.png)
