### ISSUE TITLE
system.time() function return negative time count

### ISSUE THREAD

**Issue by XD-DENG** [bedatadriven/renjin#104]
I tried to use system.time() to count the time consumed to calculate sqrt(). But sometimes it returns negative time count which is impossible. 
The screenshot is attached below.

(My laptop is using Ubuntu 14.04 and the latest version of Renjin.)

![bug_about_system time](https://cloud.githubusercontent.com/assets/11539188/7466836/8d79ab38-f31d-11e4-94e1-9cbb85526aa1.png)

**Comment by mjkallen** [comment]
Thanks for reporting! It seems that you don't get negative times if ask Renjin not to run garbage collection first:
```
> for (i in 1:10) {
+ print(system.time(sqrt(1235), gcFirst = FALSE))
+ }
       user      system     elapsed
          0 0.000179906           0
       user      system     elapsed
          0 0.000139036           0
       user      system     elapsed
          0 0.000200569           0
       user      system     elapsed
          0 0.000079037           0
       user      system     elapsed
          0 0.000075614           0
      user     system    elapsed
         0 0.00005781          0
     user    system   elapsed
        0 0.0000494         0
       user      system     elapsed
          0 0.000050025           0
       user      system     elapsed
          0 0.000048211           0
       user      system     elapsed
          0 0.000048549           0
> 
```

**Comment by XD-DENG** [comment]
Hi! Thanks for noting this and replying.

But I guess set gcFirst = TRUE is quite necessary in some situations. And this issue doesn't arise in GNU R.

I tried to compare the source code of system.time() function in Renjin and GNU R, but found no difference. So also confused about this.

I'm not that familiar with the very fundamental works of this, so maybe my thoughts are somehow stupid. Hope you don't mind.

**Comment by akbertram** [comment]
Interesting bug. 

The JVM doesn't give us the system time explicitly, so Renjin calculates the system time as the difference between [ThreadMXBean.getCurrentThreadCpuTime()](https://docs.oracle.com/javase/7/docs/api/java/lang/management/ThreadMXBean.html#getCurrentThreadCpuTime()), which includes both system and user CPU time, and [ThreadMXBean.getCurrentThreadUserTime()](https://docs.oracle.com/javase/7/docs/api/java/lang/management/ThreadMXBean.html#getCurrentThreadUserTime()), both of which return values in "value is of nanoseconds precision but not necessarily nanoseconds accuracy."

I think that the overhead of the very first call to `ThreadMXBean.getCurrentThreadCpuTime()` results in a a delay between the measurement of total time and user time that screws up the subsequent calculation of the difference between system cpu time spent before and after the evaluation of `sqrt(1234)`.

I'll update the code to round the CPU timings down to the nearest milliseconds.

**Comment by akbertram** [comment]
@XD-DENG can you confirm that this fixes the abberant behavior that you observed?
