### ISSUE TITLE
Error loading .rda file (0.7.1520)

### ISSUE THREAD

**Issue by lkorogodski** [bedatadriven/renjin#106]
The following error occurs when trying to execute

engine.eval(s"""load("$filename.rda")""")

for a .rda file. (Please note that the Scala string interpolation syntax resolves to "load("<filename>.rda")", where the inner parentheses have already been escaped, so that is not the issue.)

[info] - batch evaluation *** FAILED ***
[info]   org.renjin.eval.EvalException: Byte code expressions are not supported.
[info]   at org.renjin.primitives.R$primitive$loadFromConn2.apply(R$primitive$loadFromConn2.java:41)
[info]   at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
[info]   at org.renjin.eval.Context.evaluateCall(Context.java:261)
[info]   at org.renjin.eval.Context.evaluate(Context.java:193)
[info]   at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
[info]   at org.renjin.eval.Context.evaluateCall(Context.java:261)
[info]   at org.renjin.eval.Context.evaluate(Context.java:193)
[info]   at org.renjin.eval.Context.evaluate(Context.java:161)
[info]   at org.renjin.sexp.Closure.doApply(Closure.java:108)
[info]   at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
[info]   ...
[info]   Cause: java.io.IOException: Byte code expressions are not supported.
[info]   at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:214)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readClosure(RDataReader.java:254)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:185)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readPairList(RDataReader.java:279)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:181)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readEnv(RDataReader.java:368)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:179)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readTag(RDataReader.java:301)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readClosure(RDataReader.java:252)
[info]   at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:185)
[info]   ...

**Comment by akbertram** [comment]
It looks like your .rda file contains GNU R bytecode. There are no plans to add support for evaluating GNU R's bytecode to Renjin as we are pursuing quite different optimization strategies.

For this reason, we've never considered support for _deserializing_ the bytecode, but I can how it would be useful for the purposes of interoperability. I wonder if byte-compiled closures also include the original AST body? If so, we might be able to  just ignore the bytecode. 

Short of that, we would need some sort of bytecode decompiler to transform the bytecode back into a "normal" R AST. That wouldn't be beyond the realm of possiblity given how well documented Luke's compiler is, but it wouldn't be a trivial project either.

In the meantime, you can avoid this by compiling GNU R from source with byte code compilation disabled:

```
$ ./configure --enable-byte-compiled-packages=no && make
```

**Comment by lkorogodski** [comment]
Thanks for the response.

Our predicament is that we don't generate the .rda files. They're given to us. We only must evaluate the models against new data. One way to do that is via PMML. But I also wanted to test Renjin as an alternative.

I don't know if the .rda files contain a non-bytecode AST.

**Comment by akbertram** [comment]
I had a chance to speak with Luke from the GNU R core team and it looks like there is an easy work around this: all byte-code-compiled functions include the original AST within the constant pool, so it should be straightforward to parse just enough of the bytecode to extract the original AST and discard the rest.

See ReadBCLang, ReadBC1 etc in:
http://svn.r-project.org/R/trunk/src/main/serialize.c

**Comment by lkorogodski** [comment]
Thanks! Does that mean that it may be supported in a future release (hopefully, soon)?

**Comment by akbertram** [comment]
Yes, I think so. I'm afraid I don't know when we'll have a chance, but if
you're interested in tacking a crack at it I can walk you through it and
would be very happy to review a pull request.

On Fri, Jul 10, 2015 at 11:11 PM, lkorogodski <notifications@github.com>
wrote:

> Thanks! Does that mean that it may be supported in a future release
> (hopefully, soon)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bedatadriven/renjin/issues/106#issuecomment-120530186>
> .
>



-- 
Alex Bertram
Technical Director
be*datadriven*

*Web: http://bedatadriven.com*
Email: alex@bedatadriven.com
<alex@bedatadriven.com>Tel. Nederlands: +31(0)647205388
Skype: akbertram

**Comment by akbertram** [comment]
@lkorogodski If you have a chance, could you let me know if this works for you now?
