### ISSUE TITLE
number of variables != number of variable names (0.7.1520)

### ISSUE THREAD

**Issue by lkorogodski** [bedatadriven/renjin#107]
The following error (see below) occurs when trying to execute the R code (see below). Please note that the data file does have more columns than passed to the glm function. However, the same code works perfectly well in GNU R Console.

example <- read.table("[some data file]")

fit <- glm(column2 ~
    +column4
    +column7
    +column13
    +column7 * column15
    +column7 * column21
    +column15
    +column21
    +column30
    +column33
    ,data=example
    ,family=binomial()
    ,weights=round(1/example$outcome_weight,0))

[info]   org.renjin.eval.EvalException: number of variables != number of variable names
[info]   at org.renjin.stats.internals.models.Models.modelFrame(Models.java:151)
[info]   at org.renjin.primitives.R$primitive$model$frame.doApply(R$primitive$model$frame.java:76)
[info]   at org.renjin.primitives.R$primitive$model$frame.apply(R$primitive$model$frame.java:37)
[info]   at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
[info]   at org.renjin.eval.Context.evaluateCall(Context.java:261)
[info]   at org.renjin.eval.Context.evaluate(Context.java:193)
[info]   at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
[info]   at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
[info]   at org.renjin.eval.Context.evaluateCall(Context.java:261)
[info]   at org.renjin.eval.Context.evaluate(Context.java:193)
[info]   ...

**Comment by akbertram** [comment]
@ikorogodski I think this may have been fixed by some work on model.frame. Can you double check or add a minimal example?
