### ISSUE TITLE
Studio GUI from renjin.org download link does not work

### ISSUE THREAD

**Issue by cinterloper** [bedatadriven/renjin#111]
When going to the renjin.org website to download the studio, i receive this file:
34K Jul 11 17:47 renjin-studio-0.7.1547.jar
6f52f482d7975e3e1954e48af2d04dde  renjin-studio-0.7.1547.jar

It is not an executable jar as i would expect:

[grant@nighthawk Downloads]$ java -jar renjin-studio-0.7.1547.jar 
no main manifest attribute, in renjin-studio-0.7.1547.jar

but if i poke around i can find this:
http://nexus.bedatadriven.com/content/groups/public/org/renjin/renjin-studio/0.7.1547/renjin-studio-0.7.1547-jar-with-dependencies.jar

which does execute, out of the box. 

java -jar renjin-studio-0.7.1547-jar-with-dependencies.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Is this intentional? 
When instructing a Statistician friend of of mine on how to find and run renjin, this was very confusing.

**Comment by mjkallen** [comment]
No, this is certainly not intentional. The link on the downloads page was incorrect and you have found the correct .jar file. We have fixed the link, thanks for reporting! You can ignore the messages from SLF4J, but we will look into removing these.

**Comment by xapiens** [comment]
the renjin studio download still have this bug.
