### ISSUE TITLE
Vector.DEBUG_ALLOC is non modifiable leading to calls to System.out.println on exec

### ISSUE THREAD

**Issue by hbs** [bedatadriven/renjin#113]

**Comment by akbertram** [comment]
I know this was an issue with a past version; is it still the case with 0.7.1548?

**Comment by hbs** [comment]
My bad, I was running 0.7.0-RC8-SNAPSHOT, just tried 0.7.1548 and it's OK. Sorry for the noise.

**Comment by akbertram** [comment]
Ok, good to hear!
