### ISSUE TITLE
Support compilation of C++ package sources

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#119]
In principle, our gcc-based native source compilation toolchain should be able to handle C++ as well as C because both are reduced to the Gimple IR by GCC.

The gimple output from a C++ program, however, does include vtables which are more complicated structures than we have currently implemented.

**Comment by akbertram** [comment]
I think we've made good progress on this. But I think the one major change that we need to make is to get plugin.c to emit the mangled names. Otherwise we will have to deal with all of the complexity of matching function calls to their proper C++ overload. I've also seen in a few tests that we run into problems when you have different overloads that erase to the same JVM type signature - for example if both overloads point to structures that then they will both have signatures of (Lorg.renjin.gcc.runtime.ObjectPtr;)V and we'll generate an invalid classfile.

**Comment by akbertram** [comment]
@hwvenancio FYI I have made some progress with virtual methods

**Comment by hwvenancio** [comment]
Nice! I'll take a look, and maybe work on some more contributions. Haven't been able to dedicate time to other projects lately.

**Comment by akbertram** [comment]
Note to self: c++ exceptions are up next:
Useful blog series on how they are implemented by GCC: [C++ Exceptions under the hood](https://monoinfinito.wordpress.com/category/programming/c/exceptions/)

**Comment by akbertram** [comment]
C++ compilation is now turned on for all CRAN/BioConductor packages. Will open further tickets for specific issues affecting C or C++ code.
