### ISSUE TITLE
Implement BFGS method in optim()

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#12]
Test case: modeest/parzen-examples

**Comment by tninja** [comment]
without BFGS, arima won't run:

arima(lh, order = c(1,0,0))

org.renjin.eval.EvalException: method 'BFGS' not implemented.

**Comment by akbertram** [comment]
This has been resolved. Tested against 0.8.2504:
http://packages.renjin.org/package/org.renjin.cran/modeest/2.1/build/253#test-parzen-examples
