### ISSUE TITLE
random variate functions fail when length of inputs are greater than 1

### ISSUE THREAD

**Issue by mjkallen** [bedatadriven/renjin#120]
Take for example the `rbinom` function. In Renjin:

```
> set.seed(1)
> rbinom(10, 1, 0.5)
[1] 0 0 1 1 0 1 1 1 1 0
> set.seed(1)
> rbinom(10, 1, rep(0.5, 10)) # should give the same result as above according to ?rbinom
ERROR: Invalid argument: expected vector of length 1. Expected:
         rbinom(integer(1), double(1), double(1))
   at rbinom()
```

According to `?rbinom`: 

_The length of the result is determined by n for rbinom, and is the maximum of the lengths of the numerical parameters for the other functions. The numerical parameters other than n are recycled to the length of the result._

Also:

_n  number of observations. If length(n) > 1, the length is taken to be the number required._

The same problem occurs for `rgamma`, see for example one of the _limma_ examples [here](http://packages.renjin.org/package/org.renjin.bioconductor/limma/3.24.15/build/7#test-fitGammaIntercept-examples).

**Comment by akbertram** [comment]
Resolved. Tested on  0.8.2474
