### ISSUE TITLE
glm() with family="binomial" fails with org.renjin.eval.EvalException: object 'C_logit_link' not found

### ISSUE THREAD

**Issue by cwlaird3** [bedatadriven/renjin#122]
Looks like this has been discussed before: https://groups.google.com/forum/#!topic/renjin-dev/Zgpr_rD-F8Y

I will try Alex's suggestion of copying  http://svn.r-project.org/R/tags/R-2-14-2/src/library/stats/src/loglin.c but any C skills I once had are a distant memory.

The following unit test can be used to recreate:

``` java
package test;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

import org.junit.Test;
import org.renjin.sexp.DoubleVector;
import org.renjin.sexp.ListVector;

public class GLMTest {

    @Test
    public void testGLM() throws Exception {
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("Renjin");

        engine.eval("Conversions <- matrix(c(23, 100, 21, 100, 17, 100, 15, 100), nrow=4, ncol=2)");
        engine.eval(" X <- c(1, 1, 0, 0)");
        engine.eval(" Y <- c(1, 0, 1, 0)");

        ListVector singleCoefficientModel = (ListVector) engine
                .eval("fit <- glm(formula = Conversions ~ X + Y, family=\"binomial\")");

        DoubleVector singleCoefficients = (DoubleVector) singleCoefficientModel.getElementAsVector("coefficients");
        DoubleVector singleConfidenceIntervals = (DoubleVector) engine.eval("confint(fit, level=0.95)");
    }
}
```

**Comment by akbertram** [comment]
Thanks for the test case! I just tried to see if the current version of our C compiler could handle loglin.c but no success. We are actually working on a new version of the C compiler this week and should be able to compile this once that work is complete.

**Comment by akbertram** [comment]
@psolaimani You should incorporate part of loglin.c as a test case for #124 : we need to detect which members of structures need to be addressable and represent those fields as arrays so they can be addressed, similar to [AddressableVarGenerator](https://github.com/bedatadriven/renjin/blob/6b335beb9ad8739bd2191d9cafcfb5e3056027fb/tools/gcc-bridge/src/main/java/org/renjin/gcc/codegen/var/AddressableVarGenerator.java#L20-20)

For example:
```.C
struct params {
   int iteration_count;
}
void init_count(int *count) {
   *count = 0;
}
void main() {
   struct params p;
   init_count(&p.iteration_count);
}
```
Should be emitted as the equivalent as:
```.java
class params {
   public int [] iteration_count = new int[1];
}
void init_count(IntPtr count) {
  count.set(0);
}
void main() {
  init_count(new IntPtr(p.iteration_count))
}
```

**Comment by akbertram** [comment]
@cwlaird3 Actually was able to get loglin.c compiling on the master branch by moving c__1 inside the `loglin` function, but now your test case fails because logit_link is missing, which is implemented with .Call interface (Issue #118).

**Comment by cwlaird3** [comment]
Thanks Alex.

Is Issue #118 part of the gcc work going on this week that you mentioned?

**Comment by akbertram** [comment]
Yes, definitely. It's a big priority for us now as our main focus is supporting Bioconductor packages which rely heavily on the .Call interface. The first prerequisite is improving the compiler (Issue #124 and #125 are the last remaining pieces) but the plan is to have a working .Call interface by the end of the month.

**Comment by akbertram** [comment]
@cwlaird3 FYI, your GLM is now *almost* running, Renjin returns the correct parameter estimates, but the confint() function apparently relies on the MASS package. It's going to require a bit more work on the C API shim (#118) to get MASS running, but I don't think we're that far off.

**Comment by cwlaird3** [comment]
Excellent!  Thanks for the updates.

**Comment by cwlaird3** [comment]
Looks like issue #118 is fixed.  What is now required to get MASS working?  Thanks.

**Comment by akbertram** [comment]
I think the last bit is getting some missing math functions building. See #164

**Comment by psolaimani** [comment]
This issue seems resolved. At least the example code is running on Renjin repl correctly.
```
Conversions <- matrix(c(23, 100, 21, 100, 17, 100, 15, 100), nrow=4, ncol=2)
X <- c(1, 1, 0, 0)
Y <- c(1, 0, 1, 0)
fit <- glm(formula = Conversions ~ X + Y, family="binomial")
```

can we close this issue @akbertram?

**Comment by akbertram** [comment]
Rechecked in 3.5-beta50. Works correctly.
