### ISSUE TITLE
Exception was thrown for lm function when all values are the same. 

### ISSUE THREAD

**Issue by shaohui-liu2000** [bedatadriven/renjin#136]
When all values are the same, the lm function throws errors. But it worked on GNU R. I am using the latest renjin-script-engine-0.8.1593.jar
Caused by: org.renjin.eval.EvalException: contrasts can be applied only to factors with 2 or more levels
    at org.renjin.primitives.Conditions.stop(Conditions.java:193)
    at org.renjin.primitives.R$primitive$stop.doApply(R$primitive$stop.java:72)

When I called RenjinScriptEngine.eval(..) with this script:
fit<-lm("formula"=vals~index,"data"=data)

The data of input is

"2015-36",9
"2015-37",9
"2015-41",9.

**Comment by akbertram** [comment]
I'm not sure if this has been fixed or if I'm not reproducing it correctly, but it looks like the above now works in the current build of Renjin (0.8.1995):

```.R
data <- data.frame(vals=c(9,9,9), index=c("2015-36", "2015-37", "2015-41"))
fit <- lm("formula"=vals~index,"data"=data)
print(fit)
```
Gives the same output as GNU R 3.2.2:

```

Call:
lm(formula = vals ~ index, data = data)

Coefficients:
(Intercept)  index2015-37 index2015-41
 9           -0           -0          
```
Note that Renjin doesn't properly but the coefficients into scientific notation, but if you do:

```
> sprintf("%e", fit$coefficients)
sprintf("%e", fit$coefficients)
[1] "9.000000e+00"  "-3.076740e-15" "-3.076740e-15"
```

You'll see that the results are identical to those of GNU R.
