### ISSUE TITLE
No access to Java accessors during script evaluation

### ISSUE THREAD

**Issue by hinerm** [bedatadriven/renjin#140]
The automatic [Java Bean conveniences](http://renjin.readthedocs.org/en/latest/importing-java-classes-in-r-code.html#chap-importing-java-classes-into-r-code) actually make scripting in renjin unintuitive at first (for a Java developer), and even make some operations impossible (as far as I can tell).

For example, running the script:
```java
"import(java.util.HashMap)\n"
"ageMap <- HashMap$new()\n"
"print(ageMap$getClass())";
```

Causes:
`org.renjin.eval.EvalException: Instance of class java.util.HashMap has no member named 'getClass'`

Which would be manageable, except if I try to avoid using the accessor:

```java
"import(java.util.HashMap)\n"
"ageMap <- HashMap$new()\n"
"print(ageMap$class)";
```

I still get an `EvalException`, for "no member named class".

In other cases the automatic Bean parsing worked great. But given this, it seems like Renjin is over-aggressive in stripping away accessors.

Also, I suggest preserving both accessor and direct field members to the External_Ptrs - so code from Java will work regardless of which it was written to use.

**Comment by akbertram** [comment]
Thanks for the feedback!
I think this is a fair point - and I don't think there's any reason why we couldn't expose both the getters/setters as well as the property syntax. `ageMap$class` should also work, so I'll take a look at that.

**Comment by hinerm** [comment]
fantastic! Love the project by the way :) very easy to code against
