### ISSUE TITLE
regexpr() does not return capture.start and capture.end attributes

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#143]
For extracting strings using regular expression (regexpr), the methods attr(regexpr_output, "capture.start") and  attr(regexpr_output, "capture.end") to access coordinates is not working/implemented in Renjin (returns NULL):

In GNU R:

> a <- c("abc")
> b <- regexpr('(b)', a, perl = TRUE)
> b
> [1] 2
> attr(,"match.length")
> [1] 1
> attr(,"useBytes")
> [1] TRUE
> attr(,"capture.start")
> [1,] 2
> attr(,"capture.length")
> [1,] 1
> attr(,"capture.names")
> [1] ""

In GNU R:

> attr(b, "capture.start")
> [1,] 2
> attr(b, "capture.length")
> [1,] 1
> attr(b, "capture.names")
> [1] ""
> attr(b, "match.length")
> [1] 1

In renjin:

> attr(b, "capture.start")
> NULL

**Comment by akbertram** [comment]
Can you add a test case? Is the output above from GNU R or Renjin?

**Comment by psolaimani** [comment]
this only happens when you use **parentheses/grouping**  in **pattern** and have **perl** set to **TRUE**

so GNU R: 
`regexpr('(b)', c('abc','cab'), perl=TRUE)`
> [1] 2 3
> attr(,"match.length")
> [1] 1 1
> attr(,"useBytes")
> [1] TRUE
> attr(,"capture.start")
> [1,] 2
> [2,] 3
> attr(,"capture.length")
> [1,] 1
> [2,] 1
> attr(,"capture.names")
> [1] ""

while 
`regexpr('b', c('abc','cab'), perl=TRUE)`
> [1] 2 3
> attr(,"match.length")
> [1] 1 1
> attr(,"useBytes")
> [1] TRUE

**Comment by akbertram** [comment]
Fixed in d7db4a86fba7940f8fdc594d8fe1bd03fda21ead
