### ISSUE TITLE
java.lang.NullPointerException in org.renjin.script.RenjinBindings.put

### ISSUE THREAD

**Issue by AlexanderRay** [bedatadriven/renjin#146]
Hi, 

I get java.lang.NullPointerException by integrating Renjin with OrientDB, 
because OrientDB unbinds script bindings with binding.put("somevar", null)

```java
  @Override
  public Object put(String name, Object value) {
    Symbol symbol = Symbol.get(name);
    SEXP previousValue = frame.getVariable(symbol);
    SEXP exp = Converters.get(value.getClass()).convertToR(value);
                                ^ java.lang.NullPointerException if value is NULL
    frame.setVariable(symbol, exp);
    return previousValue;
  }
```

**Comment by AlexanderRay** [comment]
that could be for example a possible solution: 

```java   
 @Override
    public Object put(String name, Object value) {

        Symbol symbol = Symbol.get(name);
        SEXP previousValue = frame.getVariable(symbol);

        if (value == null) {
           frame.remove(symbol);
        } else {
            SEXP exp = Converters.get(value.getClass()).convertToR(value);
            frame.setVariable(symbol, exp);
        }
        return previousValue;
    }
```

**Comment by akbertram** [comment]
Hmm, good question. The Bindings interface also has a [remove()](https://docs.oracle.com/javase/7/docs/api/javax/script/Bindings.html#remove(java.lang.Object)) method, so I'm not sure that it would be entirely appropriate to treat `put(key, value)` as `remove(key)` when `value` is null. 

What I can do is make sure that Renjin doesn't choke on `null` values and sets the binding instead to R's `NULL` object. Would that work?

**Comment by akbertram** [comment]
@AlexanderRay new release should be available shortly. Would be interested to know how it works with OrientDB!

**Comment by AlexanderRay** [comment]
Hi, thanks,  it works fine as OrientDB-Server-Side-Language (http://orientdb.com/docs/last/Javascript-Command.html) with the fix that I post above. I will test the new version of renjin with your fix and post some feedback here.
