### ISSUE TITLE
dot does not work in formulas

### ISSUE THREAD

**Issue by sschwell** [bedatadriven/renjin#147]
public class RenjinDotFormulaTest {
        @Test
        public void test() throws IOException, ScriptException {
            ScriptEngineManager manager = new ScriptEngineManager();
            ScriptEngine engine = manager.getEngineByName("Renjin");
            String script = "glm(formula = vs ~ ., family = binomial, data = mtcars)";
            engine.eval(script);
        }
    }

gives:

org.renjin.eval.EvalException: object '.' not found

**Comment by jukiewiczm** [comment]
I don't want to state the obvious but this is actually making a lot of test cases fail for a variety of packages, so fixing this might increase the numbers of packages fully available.

**Comment by akbertram** [comment]
It looks like a quick fix, as far as I can tell this only needs to be added to the `terms.formula` implementation, which is called indirectly by `glm` as well `model.frame` etc.
