### ISSUE TITLE
BasePackageTest.summaryForDataFrame fails when building under Mac OSX + Vagrant

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#148]
Virtual Box: v. 5/0/14 [Box 'ubuntu/trusty32' (v20160122.0.0)]
OS X El Capitan: 10.11.2
Java Version (OS X): 1.8.0_71
Java Version (Virtual Box): 1.8.0_72

`BasePackageTest.summaryForDataFrame` fails in the `core` module

**Comment by akbertram** [comment]
This is a fun one. 
The test above (and subsequent tests probably) fail because the function `summary.data.frame` is invoked rather than `Summary.data.frame`.

This happens because the base package environment, like other package environments, is serialized to disk, using one file per symbol. So in the `target/classes/org/renjin/base` directory, you'll find:
```
Summary.data.frame.RData
summary.data.frame.RData
Summary.Date.RData
summary.default.RData
Summary.difftime.RData
summary.factor.RData
Summary.numeric_version.RData
Summary.ordered.RData
Summary.POSIXct.RData
summary.POSIXct.RData
Summary.POSIXlt.RData
```
At least on a _case insensitive filesystem_ !

On a filesystem that is *not* case sensitive, `summary.data.frame` will overwrite `Summary.data.frame`, depending on the order of iteration.

This of course leads to all sorts of problems.

**Comment by hannesmuehleisen** [comment]
By default osx's file system is case sensitive no? It's an option though...

**Comment by akbertram** [comment]
That would explain why you haven't had a problem, but if @beattyk1

**Comment by akbertram** [comment]
What I found is that the case-sensitivity of the file system only affects _building_ Renjin. During the build process, the serialized contents of the namespace are packaged in JAR files, which are case insensitive on any filesystem.

I'm reluctant to change the naming scheme for namespace symbols because this would break compatibility with previously-built packages, and there seems to be an easy-ish workaround for OS X. (See [BUILDING](https://github.com/bedatadriven/renjin/blob/master/BUILDING.md))

What I have done is add a check to the build so it will fail quickly with a comprehensible error message if the host file system is case insensitive.

**Comment by akbertram** [comment]
@beattyk1 if you have a minute, could you check if your build now fails with the message "Renjin can only be built on a case-sensitive file system." ? I've also updated the BUILDING instructions with a link on how to create a case-sensitive partition if this is indeed the case.

**Comment by beattyk1** [comment]
At work, no where near my house/laptop.  I can try when I get home.  Sorry

**Comment by akbertram** [comment]
@beattyk1 no rush!

**Comment by beattyk1** [comment]
Yes, the build now fails with the following message.

[ERROR] ***********************************************************

[ERROR] Renjin can only be built on a case-sensitive file system.

[ERROR] See BUILDING.md for more information.

[ERROR] ***********************************************************


Thanks,

Kevin

**Comment by akbertram** [comment]
Ok, great! Thanks for testing.
