### ISSUE TITLE
sample() with replace=TRUE works unexpectedly slow.

### ISSUE THREAD

**Issue by jukiewiczm** [bedatadriven/renjin#154]
Hello,
I'm not sure whether it is fine to report performance issues here, but I'll give it a try.
I ran into unexpected performance issue when performing some tests with renjin, namely the code:

`n <- 10e6`
`m <- 1e6`
`system.time(sample(m, n, replace=TRUE))`

takes around 0.1s time to evaluate on my computer using GNU R (tested with version 2.14.2), whereas it takes about an hour (literally, around 60 minutes) to evaluate on Renjin. There is clearly a problem with the 'replace' argument, because `sample(10e6, replace = T)` (without the second argument) takes forever as well. As a hint I'd like to tell you that adding 'replace = TRUE' argument to GNU R actually speed up things, which seems reasonable.

**Comment by akbertram** [comment]
Yikes! That's no good. A quick look at the [current implementation](https://github.com/bedatadriven/renjin/blame/master/core/src/main/java/org/renjin/stats/internals/distributions/Sampling.java#L30) confirms that it has a running time of O(_m_×_n_). 

From what I can see, this implementation is meant to address the most general case, in which each element in the sampling universe has it's own probability of selection. In the case where all elements have equal probability, however, the running time should indeed be closer to O(_m_).

Let me see if I can add a quick fix.

**Comment by akbertram** [comment]
This should be fixed in release 0.8.1966. I added your case above as a test case and the runtime is now in the hundreds of milliseconds range as expected!

**Comment by jukiewiczm** [comment]
That's great to hear, very quick response from your side. Thank you!
