### ISSUE TITLE
grep() function does not handle NA pattern

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#162]
The expression `grep(c("a", "b"), pattern=NA)` evaluates to `c(NA,NA)` in GNU R but throws an exception in Renjin.

**Comment by akbertram** [comment]
See http://packages.renjin.org/package/org.renjin.cran/sp/1.2-3/build/7

**Comment by akbertram** [comment]
Looks good! I wonder how man of the other text functions handle is.na(pattern) "correctly" ? For example strsplit, grepl, etc?

**Comment by akbertram** [comment]
Package sp is still failing:
http://packages.renjin.org/package/org.renjin.cran/sp/1.2-3/build/6

Looks like it's now throwing an error when encountering in NA in the vector to match against:
https://github.com/bedatadriven/renjin/blob/d468bd2d6a5c31a9512d2929a9b8524aa63288cd/core/src/main/java/org/renjin/primitives/text/Text.java#L361-L361

**Comment by psolaimani** [comment]
in strsplit() when 'x' or 'split' arguments are 'NA', renjin outputs 'null' without entering strsplit() function. Even after changing strsplit arguments types for 'x' and 'split' to Object.

**Comment by akbertram** [comment]
I see something wrong here:
https://github.com/bedatadriven/renjin/commit/9c4f2827eb6120b17eb94e2f7436388c872da65b#diff-fa924b4d55a717e9c574514dee70abb0R348

But cant login to github to comment directly.

Use isNA for na checks

in strsplit() when 'x' or 'split' arguments are 'NA', renjin outputs 'null'
without entering strsplit() function. Even after changing strsplit
arguments types for 'x' and 'split' to Object.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/bedatadriven/renjin/issues/162#issuecomment-218570614>

**Comment by akbertram** [comment]
Looks good. The sp package is still unfortunately [failing to build](http://packages.renjin.org/package/org.renjin.cran/sp/1.2-3/build/12) but it doesn't seem related to grep.

Good work!
