### ISSUE TITLE
Import source for vmmin, used by many packages including MASS

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#164]
We currently include a build of the `appl` library used by both Renjin core and by external packages; but we currently only include the Fortran sources.

The remaining files need to be imported:
- uncmin.c
- optim.c
- pretty.c
- integrate.c
- interv.c

These sources, however, depend on the GNU R header files. We need to move these out of the gnur-runtime module so that both gnur-runtime and appl can depend on them, and gnur-rutnime can depend on appl.

**Comment by PavilVenugopal** [comment]
Is there any update on this issue?

**Comment by mjkallen** [comment]
Nope. And probably not for at least a couple of weeks as we are currently on vacation :)

**Comment by akbertram** [comment]
I expect this to be implemented towards the end of May.

**Comment by cwlaird3** [comment]
Any further update here?  Thanks.

**Comment by akbertram** [comment]
These sources are now part of Renjin and (nearly) all tests and examples from the MASS package pass:
http://packages.renjin.org/package/org.renjin.cran/MASS/7.3-51.4/build/10
