### ISSUE TITLE
update.formula not yet implemented

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#170]
Ï am trying to follow the credit score example on https://mkmanu.wordpress.com/2014/08/28/modelling-credit-scoring-in-r-part-2/. I am using the Renjin studio. Version is 0.8.2009
On step 5 i get the error message: Error: Sorry! update.formula not yet implemented!

> credit <- read.csv("H:/projects/renjin/creditscore/germancredit1.csv")
> train <- 1:800
> null <- glm(GoodCredit ~ history3, family=binomial, data=credit[train, ])
> full <- glm(GoodCredit ~ ., family = binomial, data = credit[train,])
> reg <- step(null, scope=formula(full), direction="forward", k=log(length(train)))
> Error: Sorry! update.formula not yet implemented!

Please implement formula!

**Comment by psolaimani** [comment]
Thank you for reporting this issue.

Here is a minimal reproducible example:

```R
null <- glm(vs~gear, data=mtcars)
full <- glm(vs~., data=mtcars)
reg <- step(null, scope=formula(full), direction="forward")
```

which results in the following error:
```
ERROR: Sorry! update.formula not yet implemented!
java.lang.ClassNotFoundException: org.renjin.primitives.R$primitive$update$formula
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	...
	at org.renjin.cli.Main.main(Main.java:73)
  at update.formula()
  at terms()
  at step()
Caused by:java.lang.ClassNotFoundException: org.renjin.primitives.R$primitive$update$formula
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	...
	at org.renjin.cli.Main.main(Main.java:73)
```

**Comment by psolaimani** [comment]
resolved in this [PR](https://github.com/bedatadriven/renjin/commit/84b208f98dfebedd244b59f5f179a4f237a7c0bf)
