### ISSUE TITLE
Implement pure R version of pretty()

### ISSUE THREAD

**Issue by mjkallen** [bedatadriven/renjin#173]
The `pretty()` function calls out to an internal C implementation (see [here](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/appl/pretty.c)) which we should replace with a pure R version. Due to Andrew Gelman's inquisitive nature, we have all the necessary information on his blog at http://andrewgelman.com/2010/03/23/pretty_aint_alw/.

Although we don't support graphics in Renjin, there are some packages (like [txtplot](http://packages.renjin.org/package/org.renjin.cran/txtplot)) which seem to use the `pretty()` function for other purposes. The `graphics::hist()` function also calls `pretty()` and can be used in a non-plotting mode (currently disabled in Renjin).

Given the above, the goal should not be to provide a perfect replacement, but one that is close enough to what GNU R does.

**Comment by mjkallen** [comment]
Turns out that Just Talbot has implemented Heckbert's algorithm (mentioned in Gelman's post): https://github.com/cran/labeling/blob/master/R/labeling.R#L59

Should be able to use that code for the pretty() function although there may be some slight differences between GNU R and this code.

**Comment by akbertram** [comment]
The base function `pretty` seems to accept a number of arguments:

```
pretty.default <-
    function(x, n=5, min.n= n %/% 3, shrink.sml = 0.75,
             high.u.bias = 1.5, u5.bias = .5 + 1.5*high.u.bias,
             eps.correct = 0, ...)
```

I would love to drop in Justin Talbot's code, but I suspect it will just kick the can down the road until we hit a use case which relies on this specific algorithm.
