### ISSUE TITLE
Add tools:::.get_standard_package_names

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#174]
The `.get_standard_package_names` function is not exported by the tools package but is illicitly used by at least one package, causing a build regression:
http://packages.renjin.org/package/org.renjin.cran/sandwich/2.2-7/build/30

Copy the function from GNU R to `packages/tools/src/main/R" and run the [Rebuild-Build-Regressions](http://build.renjin.org/job/Packages/job/Rebuild-Build-Regressions/) job.

**Comment by akbertram** [comment]
@psolaimani can you quickly fix this issue? The red marks on our [dashboard](http://packages.renjin.org/qa/dashboard) are annoying me :-)

**Comment by mjkallen** [comment]
Loading the *tools* package from the command line doesn't seem to work:

```
> library(tools)
Loaded org.renjin.tools version 0.9.0-SNAPSHOT.
ERROR: Could not load package org.renjin:tools
  at library()
```

so adding functions to the package may not actually help.
