### ISSUE TITLE
model.matrix() result differs from GNU R

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#176]
GNU R:

```
> y <- factor(c(1,2,1,2,2))
> model.matrix(~y-1)
  y1 y2
1  1  0
2  0  1
3  1  0
4  0  1
5  0  1
attr(,"assign")
[1] 1 1
attr(,"contrasts")
attr(,"contrasts")$y
[1] "contr.treatment"
```

Renjin:

```
> y <- factor(c(1,2,1,2,2))
> model.matrix(~y-1)
  y2
1  0
2  1
3  0
4  1
5  1
attr(,"assign")
[1] 1
attr(,"contrasts")
$y
[1] "contr.treatment"
```

I don't understand why GNU R adds two dummy variables for a factor with two levels.

**Comment by csta** [comment]
I think it adds it because you have the '-1'.  In general R defaults to have an intercept term for models. It is just trying to preserve the rank. If you take out the -1, I bet it will provide a rank 2 matrix.

**Comment by psolaimani** [comment]
solved in this [PR](https://github.com/bedatadriven/renjin/commit/84b208f98dfebedd244b59f5f179a4f237a7c0bf)
