### ISSUE TITLE
Implement importMethodsFrom NAMESPACE directive

### ISSUE THREAD

**Issue by mjkallen** [bedatadriven/renjin#177]
A rather important directive to import S4 methods. Its absence is can cause [build failures](http://packages.renjin.org/package/org.renjin.cran/untb/1.7-2/build/217).

See https://github.com/bedatadriven/renjin/blob/86f58dabf493ab9f45040d79aec250c55d7cd78f/core/src/main/java/org/renjin/primitives/packaging/NamespaceFile.java#L262-L262

**Comment by akbertram** [comment]
@psolaimani here are some pointers:

Start by adding a test case in `test-packages/s4test/`. Make sure it fails before starting.

Then take a look at `NamespaceFile`. The directive needs to be parsed in a similar way to `parseImportS4ClassesFrom`. You'll want to add a new list of methods to `PackageImportEntry` class. We have fields for symbols, classes, and now add a list of methods to import.

Once you implement the parsing, you should no longer get an error from your test case when parsing the Namespace file, but your test should still fail. If it doesn't fail, then tweak the test until it does.

The real work needs to take place during the namespace initialization, which uses the information from `NamespaceFile`.

You'll find the GNU R implementation in [src/library/base/R/namespace.R](https://github.com/wch/r-source/blob/trunk/src/library/base/R/namespace.R). Our implementation is in `Namespace::initImports()`.

**Comment by akbertram** [comment]
Resolved. See: http://packages.renjin.org/package/org.renjin.cran/untb/1.7-2/build/232
