### ISSUE TITLE
mclust - build failed - easy to fix?

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#198]
I'm really interested to use mclust with renjin in some of my projects. However, the build fails but according the build.log the error seems to be easy to fix:

> Evaluating '/home/jenkins/workspace/Packages/Rebuild-NeedsCompilation@131/package/R/options.R'
> ERROR: Invalid argument:
> 	rgb256(double, double, double, double, NULL)
> 	Expected:
> 	rgb256(DoubleVector, DoubleVector, DoubleVector, DoubleVector, character)
>   at rgb()
>   at pal()
>   at structure()
>   at structure()

Just use DoubleVector instead of double?

**Comment by akbertram** [comment]
DoubleVector is actually just the Java class for the "R" double type. The issue seems to be that our implementation of `rgb256` does not accept a `NULL` argument  as the last argument.

**Comment by thorstenwagner** [comment]
Thank you for the fix! 
However, the mclust package seems to be still not working. I guess it is a larger issue beause some fortran methods are missing:
http://packages.renjin.org/package/org.renjin.cran/mclust/5.2/build/18#test-Mclust-examples

Does it make sense to open a new issue?
