### ISSUE TITLE
as.Date() with format returns incorrect values in some timezones

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#199]
minimal reproducible example:
```
set time-zone to somewhere in United States and then
engine.eval("thisDate<-\"2016-06-1\"");
engine.eval("thisDate2<-as.Date(thisDate,\"%Y-%m-%d\")");
engine.eval( "print(thisDate2)" );
```
returns
> [1] "2016-05-31"

or on Renjin (studio/cli):
```
thisDate <- "2016-06-1"
thisDate2 <- as.Date(thisDate, "%Y-%m-%d")
print(thisDate2)
```
returns
> [1] "2016-05-31"

**Comment by mjkallen** [comment]
Some more details: if you pass it a date string in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format and do not provide the `format` argument, then `as.Date()` in Renjin returns the correct result. It is only when you provide a string in the `format` argument that business is transferred to the `strptime()` function **with** `tz="GMT"`: [as.Date.character in GNU R's dates.R](https://github.com/wch/r-source/blob/8dc999700ea17b412d3006e312ac359dbff5a815/src/library/base/R/dates.R#L59). So we must conclude that `strptime()` behaves different in Renjin as compared to GNU R.
