### ISSUE TITLE
bedatadriven repository: handshake alert

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#209]
Travis ci reports me that there is a problem with your maven repository:
https://travis-ci.org/thorstenwagner/ij-trajectory-classifier

> [ERROR] Failed to execute goal on project ij_trajectory_classifier: Could not resolve dependencies for project de.biomedical-imaging.imagej:ij_trajectory_classifier:jar:0.8-SNAPSHOT: Failed to collect dependencies at org.renjin:renjin-script-engine:jar:0.8.2136: Failed to read artifact descriptor for org.renjin:renjin-script-engine:jar:0.8.2136: Could not transfer artifact org.renjin:renjin-script-engine:pom:0.8.2136 from/to bedatadriven (https://nexus.bedatadriven.com/content/groups/public/): handshake alert:  unrecognized_name -> [Help 1]

A simple search on https://nexus.bedatadriven.com gives: 

> There was an error communicating with the server: request timed out.

**Comment by akbertram** [comment]
I see one failed check on Pingdom from early this morning but otherwise connecting to the server seems normal... are you still having problems connecting to https://nexus.bedatadriven.com?

**Comment by thorstenwagner** [comment]
Ok, the search for artifacts seems to be working again.
But the travis-ci server still gives me a handshake alert:
https://travis-ci.org/thorstenwagner/ij-trajectory-classifier

**Comment by akbertram** [comment]
Gah! Ok, the issue should be resolved now.

It looks like the server was restarted at some point and an outdated configuration file for SSL was used. Can you confirm that everything is normal now?

**Comment by thorstenwagner** [comment]
Yes, the build is successfull again! Thanks a lot!
