### ISSUE TITLE
Java to R and vice-versa

### ISSUE THREAD

**Issue by srikanthBezawada** [bedatadriven/renjin#213]
Hi renjin, 

In my use-case, I need to do back and forth from Java to R and viceversa.  
Is it possible with renjin ?

Thanks,
Srikanth.

**Comment by akbertram** [comment]
Yes.
Please see the documentation at http://docs.renjin.org, specifically:
http://docs.renjin.org/en/latest/library/moving-data-between-java-and-r-code.html

**Comment by srikanthBezawada** [comment]
Thanks for the quick response @akbertram

**Comment by srikanthBezawada** [comment]
Hi again@akbertram, 
I would like to use this R package[1] in my Java application. Will it be possible sometime in the future ?

[1] - http://packages.renjin.org/package/org.renjin.bioconductor/TRONCO

Thanks,
Srikanth.

**Comment by akbertram** [comment]
Hopefully! You can help by digging into the package failures and opening specific issues here. For general discussion and questions, the mailing list is probably a better place:
https://groups.google.com/forum/#!forum/renjin-dev

**Comment by srikanthBezawada** [comment]
Thanks for the quick response @akbertram
