### ISSUE TITLE
predict method applied to simple linear model causes "Error: invalid attribute 'response'" in Renjin Studio.

### ISSUE THREAD

**Issue by buildlackey** [bedatadriven/renjin#22]
To reproduce:

ONE)
Setup data file.
In your OS shell (assuming you run *nix, cygwin):

cat > /tmp/data
sqFt,bathrooms,priceInThousands
1200,1,750
1250,2,900
2000,2.5,1500

TWO) 
Launch Studio

THREE)
Type the following in Studio window>>

values <- read.csv("/tmp/data")
newModel.lm = lm(priceInThousands ~ sqFt + bathrooms, data=values)
newdata = data.frame(sqFt=1700,   bathrooms=2)
predict(newModel.lm , newdata)

FOUR)

Observe error:

Error: invalid attribute 'response'

**Comment by akbertram** [comment]
Verified as fixed in 0.8.1580
