### ISSUE TITLE
hist() is missing C bincode method

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#223]
The hist() method is missing a C method called "bincount". From the latest GNU R we need to import both the latest version of hist.R and the corresponding C code in stem.c. Should be fine to compile with GCC bridge. Add the `hist` tests you wrote earlier.

**Comment by psolaimani** [comment]
is being addressed here: https://github.com/bedatadriven/renjin/pull/226

**Comment by akbertram** [comment]
@psolaimani closing this, re-open if I'm wrong.
