### ISSUE TITLE
ERROR: object 'C_ARIMA_transPars' not found

### ISSUE THREAD

**Issue by tninja** [bedatadriven/renjin#229]
when I try to use arima example: arima(lh, order = c(3,0,0), method = "CSS", optim.method="Nelder-Mead") ## Use "Nelder-Mead" because "BFGS" has yet to be implemented.

it report me: ERROR: object 'C_ARIMA_transPars' not found

How should we do to add this?

**Comment by akbertram** [comment]
C_ARIMA_transPars is a C function from GNU R. It might be as straightforward as just copying the C code from GNU R if the GCC Bridge Compiler can handle it. 

Take a look at @psolaimani's recent work on importing the cor() function here: https://github.com/bedatadriven/renjin/pull/225

**Comment by tninja** [comment]
Found the function in side R-3.3.1/src/library/stats/src/arima.c and put it to renjin/packages/stats/src/main/c/, when I build it with mvn package, it report me 

[ERROR] Failed to execute goal org.renjin:renjin-maven-plugin:0.9.0-SNAPSHOT:gnur-sources-compile (compile-c-sources) on project stats: │-rw-r--r-- 1 ubuntu ubuntu   7055 Mar 16 23:03 distance.c
Compilation of GNU R sources failed: Error compiling /home/ubuntu/git/renjin/packages/stats/src/main/c/arima.c to gimple: Compilation fa│-rw-r--r-- 1 ubuntu ubuntu   2008 Mar 16 23:03 d2x2xk.c
iled:                                                                                                                                   │-rw-r--r-- 1 ubuntu ubuntu  20029 Mar 16 23:03 cov.c
[ERROR] cc1: warning: command line option '-fno-rtti' is valid for C++/ObjC++ but not for C [enabled by default]

**Comment by akbertram** [comment]
This is now resolved. (tested on  0.8.2474)
