### ISSUE TITLE
stats::filter() returns zero's for large vectors as input

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#230]
Using 
```
> x <- stats::filter(rnorm(1991), -rnorm(10), method = "recursive"); all(x==0)
[1] TRUE
> length(x)
[1] 2000
```
while 
```
> x <- stats::filter(rnorm(1990), -rnorm(10), method = "recursive"); all(x==0)
[1] FALSE
> length(x)
[1] 1000
```
and
```
> x <- stats::filter(rnorm(1991), -rnorm(10), method = "convolution"); all(x == 0, na.rm = TRUE)
[1] FALSE
> length(x)
[1] 1991
```

the generated values are correct, but become all zeros after the threshold (in this case 1990, but subject to change depending on inputs).

**Comment by akbertram** [comment]
@psolaimani is this purely C code or is there R code involved as well?

**Comment by psolaimani** [comment]
R code is just does checking of arguments to call the appropriate C code (rfilter/cfilter for recursive/convolution filtering and checking dimensions to loop through columns). In this case, the issue seems to be the recursive method (rfilter), convolution method didn't return all zeros with 1e6 length vector.

**Comment by akbertram** [comment]
Is it clear how to fix it?

**Comment by psolaimani** [comment]
Not yet. there is no difference in C/R code between GNU R and Renjin. and the C code for rfilter is very simple and I don't see why at 1900th+ number everything is set to zero. 

```
/* recursive filtering */
SEXP rfilter(SEXP x, SEXP filter, SEXP out)
{
   if (TYPEOF(x) != REALSXP || TYPEOF(filter) != REALSXP
       || TYPEOF(out) != REALSXP) error("invalid input");
    R_xlen_t nx = XLENGTH(x), nf = XLENGTH(filter);
    double sum, tmp, *r = REAL(out), *rx = REAL(x), *rf = REAL(filter);

    for(R_xlen_t i = 0; i < nx; i++) {
	sum = rx[i];
	for (R_xlen_t j = 0; j < nf; j++) {
	    tmp = r[nf + i - j - 1];
	    if(my_isok(tmp)) sum += tmp * rf[j];
	    else { r[nf + i] = NA_REAL; goto bad3; }
	}
	r[nf + i] = sum;
    bad3:
	continue;
    }
    return out;
}
```

**Comment by psolaimani** [comment]
by the way, in stats::filter.R there is a conditional [`if(missing(init))`](https://github.com/bedatadriven/renjin/blob/master/packages/stats/src/main/R/filter.R#L48) while in function arguments [`init=NULL`](https://github.com/bedatadriven/renjin/blob/master/packages/stats/src/main/R/filter.R#L20), therefor this conditional will never be true, shouldn't it be `if(is.null(init))`?

**Comment by akbertram** [comment]
`missing()` is funny. `missing(init)` will be true if there is no value supplied for the `init` parameter, _even if_ the argument has a default value.

**Comment by akbertram** [comment]
Probably exiting the loop too early, and leaving the rest of the values at zero. Try adding `printf()` statements to see where and when the loop is exited.

**Comment by akbertram** [comment]
@psolaimani I'm going to take a look at this now
