### ISSUE TITLE
inconsistent return type

### ISSUE THREAD

**Issue by colomb001** [bedatadriven/renjin#236]
When executing the following code, two different classes are returned:

```
String result = "test <- c(cbind(\"2\", 1:2000)[,1],cbind(\"3\", 1:2000)[,1])";
String resultTwo = "test <- c(cbind(\"2\", 1:1000)[,1],cbind(\"3\", 1:1000)[,1])";

SEXP eval = ( SEXP ) renjin.eval( result );
System.out.println( "eval.getClass() = " + eval.getClass() );

SEXP eval1 = ( SEXP ) renjin.eval( resultTwo );
System.out.println( "eval1.getClass() = " + eval1.getClass() );
```
eval.getClass() = class org.renjin.primitives.combine.view.CombinedStringVector
eval1.getClass() = class org.renjin.sexp.StringArrayVector

Both classes extend StringVector, but I found it curious that depending on the size of the R statement, a different class  would be returned.

**Comment by akbertram** [comment]
This is a feature!

Depending on the size of the data, Renjin will use different strategies for representing a vector. Specifically, over a given length, Renjin will defer evaluation to reduce memory requirements and traffic. 

You can rely on the fact that the return value will always implement the `StringVector` interface.

**Comment by colomb001** [comment]
Good to know. Thanks!
