### ISSUE TITLE
Error in validGP(list(...)) :    must specify only one of 'font' and 'fontface'

### ISSUE THREAD

**Issue by sel9828** [bedatadriven/renjin#237]
When I use gpar to specify the font family (e.g., bold, italic, etc), I get the following error:

```
in validGP(list(...)) : 
  must specify only one of 'font' and 'fontface'
```

This error is saying that I have tried to use both `font`and `fontface` in the same function, however I only wrote one in the function. I think this might be a bug, could you please try to address?
Thank you!

**Comment by akbertram** [comment]
Can you tell me about the context in which you're getting this error?

Renjin unfortunately does not yet support the graphics/grDevices packages, but if it's blocking non-graphics code from running I think we can just stub it out until we're ready to properly implement graphics.

**Comment by akbertram** [comment]
Closing as no further details are available.
