### ISSUE TITLE
Error: maximum number of connections exceeded 

### ISSUE THREAD

**Issue by PavilVenugopal** [bedatadriven/renjin#238]
I am trying to read multiple files in a for loop(around 200 files). I get this error on repeating the read operation. I have used commands "close(file)" to close the connection which does not work.

for(i in 1 :30)
{
for(j in 1:10)
     {
file1 <- file(paste("/Users/X",i,"_",j,".txt",sep=""))
data <- read.delim(file1,header=FALSE)
close(file1)
     }
}

**Comment by akbertram** [comment]
Should be fixed in 0.8.2199.

**Comment by PavilVenugopal** [comment]
Thanks, it works with 0.8.2199.
