### ISSUE TITLE
Distribution functions (runif, rnorm, rgamma, rchisq...) don't accept vector arguments

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#242]
RandomNumberGenerator dependent distribution functions such as `rnorm()`, `runif()`, `rchisq`, `rweibull`, and `rgamma` etc have `(int arg0, double arg1, double arg2)` as signature, while they should also accept vectors for at least `arg0` and `arg2`

```
> set.seed(1)
> runif(6,1,1:3)
[1] 1.000000 1.265509 1.744248 1.000000 1.572853 2.816416
> set.seed(1)
> runif(1:6,1,1:3)
[1] 1.000000 1.265509 1.744248 1.000000 1.572853 2.816416
```

extension of issue #24

**Comment by mjkallen** [comment]
@psolaimani this is a duplicate of #24, go ahead and close the old issue if you think that this one provides more detail.
