### ISSUE TITLE
bitwise functions from base package not implemented

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#262]
Bitwise operations all fail in Renjin.

In GNU R:
`bitwAnd(15L, 7L)`
[1] 7
`bitwOr(15L, 7L)`
[1] 15
`bitwXor(15L, 7L)`
[1] 8
`bitwXor(-1L, 1L)`
[1] -2
`bitwShiftR(-1, 1:31)`

**Comment by akbertram** [comment]
@psolaimani Looks like these were added sometime after the original fork from GNU R.

You can add them easily by defining:

```.java
@Internal
@DataParallel
public static int bitwAnd(int a, int b) {
  return a & b;
}
```

Be sure to generate tests because I don't know how attributes, etc, are handled.
