### ISSUE TITLE
Renjin does not accept "*" as a regular expression

### ISSUE THREAD

**Issue by jheusser** [bedatadriven/renjin#263]
Using renjin 0.8.2239:
```
> library('org.renjin.cran:csvread')
Loaded org.renjin.cran.csvread version 1.2-b242.
ERROR: IOException while loading package org.renjin.cran:csvread: Exception setting up imports/exports for namespace csvread: Invalid export pattern '*': Missing operand to closure at char 1
org.renjin.eval.EvalException: Exception setting up imports/exports for namespace csvread: Invalid export pattern '*': Missing operand to closure at char 1
```

**Comment by akbertram** [comment]
That's actually not a valid regex...  I'm surprised that this passes CRAN check, but I guess it should be ignored?

**Comment by akbertram** [comment]
Hmm... actually it looks like GNU R considers "*" to be valid regex.

**Comment by akbertram** [comment]
So this error is resolved, but unfortunately the csvread package is still unlikely to work to shortcomings in the process of compiling the C code in the package to JVM bytecode.

**Comment by jheusser** [comment]
Excellent, thanks for the improvement.
