### ISSUE TITLE
library() help directive not implemented

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#273]
`affy::read.affybatch` uses version information by calling `library(help=affy)`

see affy/R/read.affybatch.R:67:
`preproc(description)$affyversion <- library(help=affy)$info[[2]][[2]][2]`

and affy/R/read.affybatch.R:286:
`description@preprocessing$affyversion <- library(help=affy)$info[[2]][[2]][2]`

a minimal example
```
library(affy)
library(help=affy)
```

In Renjin 
> ERROR: Could not load package NA; tried org.renjin.bioconductor:NA, org.renjin.cran:NA
> Could not resolve org.renjin.bioconductor:NA
>   at library()
> Tried:
> Could not resolve org.renjin.cran:NA
> Tried:

in GNU R

>                 Information on package ‘affy’
> 
> Description:
> 
> Package:            affy
> Version:            1.52.0
> Title:              Methods for Affymetrix Oligonucleotide Arrays
> Author:             Rafael A. Irizarry <rafa@jhu.edu>, Laurent Gautier
>                     <lgautier@gmail.com>, Benjamin Milo Bolstad
>                     <bmb@bmbolstad.com>, and Crispin Miller
>                     <cmiller@picr.man.ac.uk> with contributions from
>                     Magnus Astrand <Magnus.Astrand@astrazeneca.com>,
>                     Leslie M. Cope <cope@mts.jhu.edu>, Robert
>                     Gentleman, Jeff Gentry, Conrad Halling
>                     <challing@agilixcorp.com>, Wolfgang Huber, James
>                     MacDonald <jmacdon@u.washington.edu>, Benjamin I.
>                     P. Rubinstein, Christopher Workman
>                     <workman@cbs.dtu.dk>, John Zhang
> Maintainer:         Rafael A. Irizarry <rafa@jhu.edu>
> Depends:            R (>= 2.8.0), BiocGenerics (>= 0.1.12), Biobase (>=
>                     2.5.5)
> Imports:            affyio (>= 1.13.3), BiocInstaller, graphics,
>                     grDevices, methods, preprocessCore, stats, utils,
>                     zlibbioc
> Suggests:           tkWidgets (>= 1.19.0), affydata, widgetTools
> LinkingTo:          preprocessCore
> Description:        The package contains functions for exploratory
>                     oligonucleotide array analysis. The dependence on
>                     tkWidgets only concerns few convenience functions.
>                     'affy' is fully functional without it.
> License:            LGPL (>= 2.0)
> Collate:            ProgressBarText.R ppset.ttest.R ppsetApply.R
>                     expressoWidget.R getCDFenv.R AffyRNAdeg.R avdiff.R
>                     barplot.ProbeSet.R bg.Affy.chipwide.R bg.R
>                     expresso.R fit.li.wong.R
>                     generateExprVal.method.avgdiff.R
>                     generateExprVal.method.liwong.R
>                     generateExprVal.method.mas.R
>                     generateExprVal.method.medianpolish.R
>                     generateExprVal.method.playerout.R hlog.R justrma.R
>                     loess.normalize.R maffy.R mas5.R merge.AffyBatch.R
>                     normalize.constant.R normalize.contrasts.R
>                     normalize.invariantset.R normalize.loess.R
>                     normalize.qspline.R normalize.quantiles.R
>                     pairs.AffyBatch.R plot.density.R plotLocation.R
>                     plot.ProbeSet.R pmcorrect.mas.R AffyBatch.R
>                     mva.pairs.R ProbeSet.R read.affybatch.R rma.R
>                     summary.R tukey.biweight.R whatcdf.R xy2indices.R
>                     zzz.R
> biocViews:          Microarray, OneChannel, Preprocessing
> LazyLoad:           yes
> NeedsCompilation:   yes
> Packaged:           2016-10-17 22:08:30 UTC; biocbuild
> Built:              R 3.3.1; x86_64-pc-linux-gnu; 2016-11-10 14:39:03
>                     UTC; unix
> 
> Index:
> 
> .setAffyOptions         ~~function to set options ~~
> AffyBatch-class         Class AffyBatch
> AffyRNAdeg              Function to assess RNA degradation in
>                         Affymetrix GeneChip data.
> MAplot                  Relative M vs. A plots
> ProbeSet-class          Class ProbeSet
> ProgressBarText-class   Class "ProgressBarText"
> SpikeIn                 SpikeIn Experiment Data: ProbeSet Example
> affy-options            Options for the affy package
> affy.scalevalue.exprSet
>                         Scale normalization for expreSets
> barplot.ProbeSet        show a ProbeSet as barplots
> bg.adjust               Background adjustment (internal function)
> bg.correct              Background Correction
> cdfFromBioC             Functions to obtain CDF files
> cdfenv.example          Example cdfenv
> cleancdfname            Clean Affymetrix's CDF name
> debug.affy123           Debugging Flag
> express.summary.stat    Compute a summary expression value from the
>                         probes intensities
> expresso                From raw probe intensities to expression values
> expressoWidget          A widget for users to pick correction methods
> fit.li.wong             Fit Li and Wong Model to a Probe Set
> generateExprSet-methods
>                         generate a set of expression values
> generateExprVal.method.avgdiff
>                         Generate an expression value from the probes
>                         informations
> generateExprVal.method.playerout
>                         Generate an expression value from the probes
>                         informations
> hlog                    Hybrid Log
> justRMA                 Read CEL files into an ExpressionSet
> list.celfiles           List the Cel Files in a Directory/Folder
> loess.normalize         Deprecated functions in package 'affy'
> mas5                    MAS 5.0 expression measure
> mas5calls               MAS 5.0 Absolute Detection
> merge.AffyBatch         merge two AffyBatch objects
> mva.pairs               M vs. A Matrix
> normalize.AffyBatch     Normalize Affymetrix Probe Level Data - methods
> normalize.AffyBatch.quantiles
>                         Quantile Normalization
> normalize.AffyBatch.quantiles.robust
>                         Robust Quantile Normalization
> normalize.constant      Scale probe intensities
> normalize.contrasts     Normalize intensities using the contrasts
>                         method
> normalize.invariantset
>                         Invariant Set normalization
> normalize.loess         Scale microarray data
> normalize.qspline       Normalize arrays
> pairs.AffyBatch         plot intensities using 'pairs'
> plot.ProbeSet           plot a probe set
> plotDensity             Plot Densities
> plotLocation            Plot a location on a cel image
> pmcorrect               PM Correction
> ppsetApply              Apply a function over the ProbeSets in an
>                         AffyBatch
> probeMatch-methods      Methods for accessing perfect matches and
>                         mismatches
> probeNames-methods      Methods for accessing the Probe Names
> read.affybatch          Read CEL files into an AffyBatch
> read.probematrix        Read CEL file data into PM or MM matrices
> rma                     Robust Multi-Array Average expression measure
> summary                 Probe Set Summarizing Functions
> tukey.biweight          One-step Tukey's biweight
> whatcdf                 Find which CDF corresponds
> xy2indices              Functions to convert indices to x/y (and
>                         reverse)
> 
> Further information is available in the following vignettes in
> directory ‘/home/parham/R/x86_64-pc-linux-gnu-library/3.3/affy/doc’:
> 
> affy: 1. Primer (source, pdf)
> builtinMethods: 2. Built-in Processing Methods (source, pdf)
> customMethods: 3. Custom Processing Methods (source, pdf)
> vim: 4. Import Methods (source, pdf)
>

**Comment by akbertram** [comment]
@psolaimani can you add a minimal test case to the ticket?

**Comment by psolaimani** [comment]
```
library(hamcrest)
library(utils)
assertThat( is.element(c("Version"),unlist(strsplit(library(help=utils)$info[[1]],":"))), identicalTo(TRUE))
assertThat( library(help=utils)$name, identicalTo("utils"))
assertThat( dir.exists(library(help=utils)$path, identicalTo(TRUE))
```
