### ISSUE TITLE
Piping Standard Input and Standard Output

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#285]
The [kntir](https://cran.r-project.org/web/packages/knitr/knitr.pdf) library documentation states:

> The arguments input and output do not have to be restricted to files; they can be stdin() / stdout()
> or other types of connections, but the pattern list to read the input has to be set in advanc

The documentation for [StdInConnection](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/primitives/io/connections/StdInConnection.java) states:

> Connection object for the standard input stream.
> Currently a stub, will throw an exception if actually used.

What I'd like to do, algorithmically, follows:

1. Start the R Engine.
1. Load the `knitr` library.
1. Configure `knitr` to read from `stdin` and write to `stdout`.
1. Read a String instance from an arbitrary data source (e.g., database, UI text area, etc.).
1. Pipe that String to `stdin`.
1. Execute `knitr` (should read that String's value from `stdin`).
1. Pipe `stdout` to a StringReader instance.
1. Write the resulting String read from `stdout` to an arbitrary data sink.

Is this possible, in theory, using Renjin, knitr, and standard i/o?

If not, what's another approach that allows knitr to run on arbitrary Java String instances, rather than absolute filename paths?

**Comment by akbertram** [comment]
Take a look at the `textConnection()` method. I'm not sure if writing is fully implemented in Renjin but I know that you can read from a textConnection(), which would allow you to tell knitr to read from your string.

**Comment by DaveJarvis** [comment]
Looks like Renjin [isn't compatible](http://packages.renjin.org/package/org.renjin.cran/knitr/1.15.1/build/13) with knitr at the moment.
