### ISSUE TITLE
Consider a logger package instead of code duplication

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#287]
Sprinkling `if( verbose )` throughout the code base is a bit verbose, and clutters `stdout` should any call to `cat()` be missing the conditional, such as [line 45](https://github.com/bedatadriven/renjin/blob/master/core/src/main/R/base/source.R#L45) in source.R.

Duplicating the conditional would fix the issue, but a more maintainable solution is to use a logger, such as [log4r](https://github.com/johnmyleswhite/log4r), so as to avoid code duplication altogether.

**Comment by akbertram** [comment]
I think it's a great suggestion but for the most part we're trying to avoid rewriting upstream R code from GNU R. source.R comes directly from:
https://github.com/wch/r-source/blob/trunk/src/library/base/R/source.R

**Comment by mjkallen** [comment]
But where does the call to `cat()` come from @akbertram? It's not wrapped in a `if (verbose)` statement and it's not present in the GNU R sources either...

**Comment by akbertram** [comment]
That's a good question...
