### ISSUE TITLE
Performance Profile

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#288]
Here are a few places for some quick optimization wins, according to the application I profiled.

## [EvalException](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/eval/EvalException.java)

Implement `fillInStackTrace()`:

```
@Override
public Throwable fillInStackTrace() { return this; }
```

## [Context](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/eval/Context.java)

Since `Profiler.ENABLED` is dynamic (`Boolean.getBoolean("renjin.profile");`), the compiler cannot optimize away the following lines when profiling is disabled:

```
    boolean profiling = Profiler.ENABLED && fn instanceof Symbol && !((Symbol) fn).isReservedWord();
    if(Profiler.ENABLED && profiling) {
      Profiler.functionStart((Symbol)fn, functionExpr);
}
```

Consider moving the profile code out of `Context` and into a subclass, such as `ProfilerContext` so that [lines 291 to 318](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/eval/Context.java#L291) can be as streamlined as possible. In theory, HotSpot heuristics should eventually make those checks disappear, but it might take a while.

Either way, profiling code probably belongs elsewhere. For example:

```
  private SEXP evaluateCall(FunctionCall call, Environment rho) {
   ...
    startEvaluate();
    try {
  ...
    } finally {
      stopEvaluate();
    }
}
```

Then have empty methods for `startEvaluate` and `stopEvaluate` within `Context.java`. Subclasses can then hook into the evaluation as required (e.g., for profiling or other uses). Either the compiler or the JVM can easily eliminate dead code (empty methods).

**Comment by akbertram** [comment]
For `ControlFlowExceptions`, used for `break`, `next`, and `return()`, we do indeed use the new Java 7 API to avoid the expense of creating a stacktrace:
https://github.com/bedatadriven/renjin/blob/e211649513948abd4bbe355ecfe65aa803540d6a/core/src/main/java/org/renjin/primitives/special/ControlFlowException.java#L30-L30

However, EvalException indicates that something has gone wrong in the evaluation and a stacktrace is used to display both the R stack trace and the Java stack trace to the user or developer for diagnostics. 

Do you have a specific workflow where there is a frequency of R conditions or exceptions being thrown and caught? Can you share a benchmark?

For the profiling, we were careful to ensure that the profiling code did not introduce any performance regressions, at least not on the benchmarks we have in our library. 

Hotspot, and other JVMs with JIT compilers are quite complicated and it can be difficult to predict what can and cannot be optimized away unless it's actually measured. If you can share a benchmark that could help us measure the impact of the profling code in a way that is to date missed by our existing benchmarks that would be very helpful, but in the meantime I'm going to close the issue.
