### ISSUE TITLE
setwd on Windows

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#289]
## Replicate
Java code:

```
Path wd = getWorkingDirectory();
getScriptEngine().eval( "setwd( '" + wd + "');" );
```

## Expected Results
Works on Unix and Windows.

## Actual Results
On Windows:

```
WARNING: unrecognized escape(s) removed from "C:\cygwin\home\Username\dev"
```

## Work Around
Replace the backslashes with forward slashes:
```
wd.toString().replace( '\\', '/' )
```

## Details
The work around solves the issue, but it seems the underlying code for `setwd` isn't as platform independent as it could be?

**Comment by akbertram** [comment]
In this case the `wd` Java string value is being interpreted as a R string literal. If choose to invoke setwd() in this way, you will indeed need to escape your string values properly, and not just for the backslash character but all characters that have special meaning in R string literals.

In general, you should avoid using string concatenation to compose R program strings and rely on the javax.script API instead:

```.R
Path wd = getWorkingDirectory();
getScriptEngine().put("wd", wd.toString());
getScriptEngine().eval( "setwd(wd)");
```

**Comment by DaveJarvis** [comment]
> In general, you should avoid using string concatenation to compose R program strings and rely on the javax.script API instead:

For context, here's an R startup script that bootstraps the application using a user-defined variable:

![r-startup](https://cloud.githubusercontent.com/assets/2131950/22256240/0c63492c-e20f-11e6-8dc8-847be5eb223e.png)

**Comment by akbertram** [comment]
Consider placing all your template variables like $date.anchor$ simply into the global environment, otherwise you will need to escape '\', newlines, single quotes, etc. before substituting.

**Comment by DaveJarvis** [comment]
The template variables are shared between R and non-R environments. The variables are sourced from an external YAML file, but the data source could equally be a SQL database, JSON document, TOML file, or any structured format. It is possible to escape them before substitution within the R startup script, though. Ideally, the code would look like:

```
String rSafeVariableValue = getScriptEngine().escape( rUnsafeVariableValue );
```

Would this be a suitable feature request?

**Comment by akbertram** [comment]
If you're composing R code, you would need different escape routines for different types.
You can use [StringLiterals.format()](http://javadoc.renjin.org/latest/org/renjin/parser/StringLiterals.html#format(java.lang.String,%20java.lang.String)) for formatting string literals.

But presumably if you have a `Map<String, String>` from somewhere which you are using to perform substitutions on the script, you could just easily make them available to the ScriptEngine directly:

```
for(Entry<String, String> entry : templateVariables.entrySet()) {
   scriptEngine.put(entry.getKey(), entry.getValue());
}

Then the startup script can just reference them by name.
