### ISSUE TITLE
Convert CSV file to Markdown format using read.table

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#290]
# Replicate
1. Create `filename.csv` using:

```
Item,Kilowatts,Use,Cost
Geothermal,1250.0,Electricity,0.0
Houses,13.7,Shelter,4.2
Compostor,1.2,Recycling,0.2
Farm,-840.0,Food,5.8
Pump Station,-191.6,Water,0.2
Electric Grid,-35.4,Power,0.1
Robocars,-31.7,Delivery,0.4
Robotics,-23.5,Automation,2.0
Sanitation,-17.7,Sewage,0.3
Fire Station,-9.6,Protection,0.5
Roads,0,Transport,0.9
```

2. Create `csv.R` using:

```
csv2md <- function( f ) {
  df <- read.table( f, sep=',', header=T )

  paste0( 
    paste( names( df ), collapse = '|'), '\n',    
    paste( rep( '---', length( df ) ), collapse = '|'), '\n',    
    paste( Reduce( function( x, y ) { paste( x, y, sep = '|' ) }, df ),
      collapse = '|\n' )
  ) 
}
```

3. Run R using the data file and `csv2md` function:

```
source('csv.R')
csv2md('data.csv')
```

4. Use Renjin to run `csv2md` on the same source file.

## Actual Results
Renjin returns a StringArrayVector with one element that contains:

```
Item|Kilowatts|Use|Cost   ---|---|---|---   1|1250|1|0| 2|13.7|2|4.2| 3|1.2|3|0.2| 4|-840|4|5.8| 5|-191.6|5|0.2| 6|-35.4|6|0.1| 7|-31.7|7|0.4| 8|-23.5|8|2| 9|-17.7|9|0.3| 10|-9.6|10|0.5| 11|0|11|0.9
```

## Expected Results
Renjin returns:

```
Item|Kilowatts|Use|Cost\n---|---|---|---\nGeothermal|1250|Electricity|0|\nHouses|13.7|Shelter|4.2|\nCompostor|1.2|Recycling|0.2|\nFarm|-840|Food|5.8|\nPump Station|-191.6|Water|0.2|\nElectric Grid|-35.4|Power|0.1|\nRobocars|-31.7|Delivery|0.4|\nRobotics|-23.5|Automation|2|\nSanitation|-17.7|Sewage|0.3|\nFire Station|-9.6|Protection|0.5|\nRoads|0|Transport|0.9
```

**Comment by akbertram** [comment]
I get exactly your expected result from Renjin 0.8.2242:

```
alex@alex-spectre:~$ renjin
Using local repository: /home/alex/.m2/repository
Renjin 0.8.2242
Copyright (C) 2016 The R Foundation for Statistical Computing
Copyright (C) 2016 BeDataDriven
Using system BLAS libraries.
> csv2md <- function( f ) {
+   df <- read.table( f, sep=',', header=T )
+ 
+   paste0( 
+     paste( names( df ), collapse = '|'), '\n',    
+     paste( rep( '---', length( df ) ), collapse = '|'), '\n',    
+     paste( Reduce( function( x, y ) { paste( x, y, sep = '|' ) }, df ),
+       collapse = '|\n' )
+   ) 
+ }
> csv2md("/tmp/test.csv")
[1] "Item|Kilowatts|Use|Cost\n---|---|---|---\n1|1250|1|0|\n2|13.7|2|4.2|\n3|1.2|3|0.2|\n4|-840|4|5.8|\n5|-191.6|5|0.2|\n6|-35.4|6|0.1|\n7|-31.7|7|0.4|\n8|-23.5|8|2|\n9|-17.7|9|0.3|\n10|-9.6|10|0.5|\n11|0|11|0.9"
```

Note that just calling StringArrayVector.toString() will not escape newlines as "\n". The function (correctly) returns actual newlines just as GNU R does, but when you call `print()` on the result, both Renjin and GNU R will escape newlines as "\n".

**Comment by DaveJarvis** [comment]
> but when you call `print()` on the result, both Renjin and GNU R will escape newlines as "\n".

The `print()` function isn't being called anywhere in my code, which looks like:

```
final Object result = eval( r );

// Append the string representation of the result into the text.
sb.append( result );
```

Escaping of newlines aside, what concerns me the most is that the text is being converted to numeric values:

    Item|Kilowatts|Use|Cost\n---|---|---|---\nGeothermal|1250|Electricity|0|

    tem|Kilowatts|Use|Cost   ---|---|---|---   1|1250|1|0|

Here `Geothermal` is returned as `1` and `Electricity` is returned as `1`, as though Renjin is using the row names instead of the values from the data frame.

**Comment by akbertram** [comment]
Ah, this is because read.csv converts your strings to factors, which are represented as integers in R. 

GNU R's paste implementation apparently first calls as.character() to convert its arguments to character vectors, which leads to an S3 call to as.character.factor(), while Renjin only performs a basic coercion from integer to character without checking for S3 methods. 

A minimally test case would be:

```
x <- as.factor(c("Geothermal", "Electricity"))
paste(x[1],x[2])
```

GNU R prints:
```
[1] "Geothermal Electricity"
```

while Renjin prints:
```
[1] "2 1"
```

I'll add a few test cases and a fix later today.

**Comment by DaveJarvis** [comment]
[Line 52](https://github.com/bedatadriven/renjin/commit/f880748ffaf09ac537884148bf66b2786ce325f9#diff-fa924b4d55a717e9c574514dee70abb0R52) of Text reads:

```
    List<StringVector> argumentVectors = new ArrayList<>();
```

There are a few issues with this.

First, the default capacity for ArrayList is 10, so if the number of arguments exceeds this value, there is a bit of a sub-par performance.

Second, and this is likely cross-Renjin, it would be superb if ArrayList instances--and other Collection items--could be replaced with a [superior list implementation](http://www.magicwerk.org/page-collections-overview.html) for additional performance gains.

Third:

```
FunctionCall.newCall(Symbol.get("as.character")
```

Since that value seems to be static, it might be a bit more efficient to move the value out of the loop, if possible, to re-use the function call, rather than re-instantiate it per iteration.

Last:

```
       if(!(result instanceof StringVector)) {
         throw new EvalException("as.character() returned non-character");
       }
```

It might be possible to eliminate the instanceof check in favour of a try/catch:

```
try {
        argumentVectors.add((StringVector) result);
} catch( final Exception e ) {
         throw new EvalException("as.character() returned non-character");
}
```

The instanceof check will always run, but the exception will only be thrown if the class cast fails. Since the class cast is always performed, and always checked, it should be a bit faster.

**Comment by akbertram** [comment]
Pull requests welcome!

Add a benchmark to https://github.com/bedatadriven/renjin-benchmarks and you can evaluate the effectiveness at the optimizations at http://packages.renjin.org/benchmarks

**Comment by DaveJarvis** [comment]
Automated benchmarks with notifications on performance degradation?

**Comment by akbertram** [comment]
That's the goal! I'm working on a analysis using the [changepoint](http://packages.renjin.org/package/org.renjin.cran/changepoint) package to identify "true" regressions from the otherwise noisy results, but in the meantime we have to just eyeball it:

This [graph](http://packages.renjin.org/benchmarks/machine/gce-n1-standard-4/benchmark/att/fft) for example alerted us to a regression when we fixed the fft() routine.

**Comment by DaveJarvis** [comment]
I've issued a feature request to Github to simplify pull requests:

![disabled-function](https://cloud.githubusercontent.com/assets/2131950/22164088/82993726-df0a-11e6-884d-f161394de659.png)

It'd be rather convenient to edit files online with one-click on that icon that's currently disabled.

Kudos on the automated benchmarks!

**Comment by akbertram** [comment]
If you switch to the master branch you should be able to edit inline!

**Comment by DaveJarvis** [comment]
> If you switch to the master branch you should be able to edit inline!

Yeah, the UI should do that for me. :-)
