### ISSUE TITLE
Renjin studio artifact has outdated copyright statement

### ISSUE THREAD

**Issue by lrbrinks92** [bedatadriven/renjin#298]
Renjin studio artifact has outdated copyright statement:

```
Renjin 0.8.2321
Copyright (C) 2013 The R Foundation for Statistical Computing
Copyright (C) 2014 BeDataDriven
> 
```

**Comment by mjkallen** [comment]
The greeting is defined [here](https://github.com/bedatadriven/renjin/blob/master/studio/src/main/java/org/renjin/studio/console/Repl.java#L124) and should indeed be updated (or made to update automatically).
