### ISSUE TITLE
Detect if a package is running in/installed by renjin

### ISSUE THREAD

**Issue by krlmlr** [bedatadriven/renjin#301]
Is there a way for an R package to detect if it is running in Renjin? It should be sufficient to check during package installation time.

Use case: provide a fallback native R implementation for functions that have been implemented in C/C++ for efficiency.

CC @mjkallen.

**Comment by akbertram** [comment]
Renjin adds an "engine" element to R.Version() with the value "Renjin". So you can check with `identical(R.Version()$engine, "Renjin")`
