### ISSUE TITLE
How to use renjin-repacked

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#317]
Hi, 

I tried to use the latest renjin version in one of my projects and get the following exception:
```
java.lang.NoClassDefFoundError: org/renjin/repackaged/guava/collect/Lists
	at org.renjin.script.RenjinScriptEngineFactory.getNames(RenjinScriptEngineFactory.java:72)
	at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:229)
	at 
```
I guess it has something to do with this repository:
https://github.com/bedatadriven/renjin-repackaged

However, I was not able to generate a jar file from this directory. Could you give a explanation how to resolve this issue using renjin-repackaged?

Best,
Thorsten

**Comment by akbertram** [comment]
It looks like you're missing renjin-guava from your classpath. The repackaged version of guava, which helps us avoid all kinds of guava-version-conflict nastyness is indeed built from the repository you linked to. To build, run:

    cd guava && mvn install

However, a build for both the repackaged guava and asm libraries is available from here:

https://nexus.bedatadriven.com/content/groups/public/org/renjin/renjin-guava/17.0b/
