### ISSUE TITLE
Strange behavior when using Renjin with Fiji

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#322]
Hi,

I'm using Renjin (+randomForest) in connection with Fiji and get strange results. In Fiji, the error rate is twice as high as when I run the classifier directly from eclipse. However, the renjin-script-engine version and randomForest package version is the same in both runs.

I've already gave a description of the issue here:
http://forum.imagej.net/t/renjin-randomforest-and-fiji/5532

Maybe you have an idea what could interfere with Renjin?

Best,
Thorsten

**Comment by akbertram** [comment]
So two different runs on the same version of Renjin produce different results? Is it possible that you're using different versions of Renjin and there's a regression in the latest version of Renjin?

Is Renjin being used by multiple threads in Fiji? That is totally supported, but it could be the source of the bug.

**Comment by thorstenwagner** [comment]
Is there any version number that I can check during run? I replaced in Fiji all packages I can think of. At the moment I check two version numbers and they are the same when running in eclipse or Fiji:

engine.eval("v <- version");
SEXP s = (SEXP) engine.eval("v$version.string");
IJ.log("Version Renjin: " + s);
engine.eval("v <- packageVersion(\"randomForest\")");
s = (SEXP) engine.eval("toString(v)");
IJ.log("Version RF: " + s);

**Comment by akbertram** [comment]
You can evaluate:

     print(R.Version()$version.string)

**Comment by thorstenwagner** [comment]
This is the same which I'm already check:
```
engine.eval("v <- version");
SEXP s = (SEXP) engine.eval("v$version.string");
```

And the output is the same for the eclipse and the fiji run.

**Comment by akbertram** [comment]
Ah ok, sorry, that is the same. 

I looked at the list of jars in the post linked above and I see several of Renjin's jar from the older version:

gcc-runtime-0.8.1906.jar
methods-0.8.1906.jar
grDevices-0.8.1906.jar
etc

I can't really explain why that would lead to a higher error rate but try upgrading them all? All Renjin's jars will have version 0.8.1906 in the jar file name.

**Comment by akbertram** [comment]
The other thing that has saved my life in the past is running the JVM with the option "-verbose:class".

This will tell you exactly where classes are being loaded from - the output is very long but you can verify that all the classes from the org.renjin package are being loaded from the JARs that you expect.

**Comment by thorstenwagner** [comment]
Thanks! I'm out office and will try it tomorrow morning. I keep you updated.

**Comment by ctrueden** [comment]
@thorstenwagner It sounds like dependency version skew is a likely culprit here. Note that you can update the Renjin version of Fiji using `mvn -Dimagej.app.directory=/Applications/Fiji.app -Ddelete.other.versions=true` (where `/Applications/Fiji.app` is the path to your Fiji installation) from the working directory of your component. That will copy all the dependencies transitively, replacing other versions, which should hopefully avoid dependency skew.

**Comment by thorstenwagner** [comment]
@akbertram Thanks! This resolved the issue. I replaced the following files with the latest:
datasets-0.8.1906.jar
gcc-runtimg-0.8.1906.jar
graphics-0.8.1906.jar
grDevices-0.8.1906.jar
methods-0.8.1906.jar
utils-0.8.1906.jar
stats-0.8.1906.jar

@ctrueden Thanks for the hint! I will try it next time.
