### ISSUE TITLE
mlbench

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#324]
Hi,

I would like to use automated feature selection in my software.  The RFE method from the mlbench is working quite nicely in R but unfortunately 2 of 34 tests are failing in Renjin.
Is it easily to fix? Or are you aware of another package for automated feature selection which works with Renjin?

Thanks a lot!

Best,
Thorsten

**Comment by akbertram** [comment]
Right now our build system is a little more strict than CRAN's and will only load packages during testing that are are listed in the Depends, Imports, or LinkingTo fields of the DESCRIPTION file. (Including the "Suggests" packages creates circular dependencies between packages)

In these two examples, mlbench tries to load the lattice package, which is not listed as a dependency. All the other examples run without error. 

However, do note that the package doesn't include any "real" tests beyond the package examples, so you might want to do a bit of your own testing to verify that you get the results you expect.
