### ISSUE TITLE
VSURF: org.renjin.gcc.runtime.DoublePtr to org.renjin.gcc.runtime.IntPtr 

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#325]
Hi,

after realizing that the RFE method of the caret (not mlbench (I mixed thinks up in a previous issue)!) package will not work, as the caret package have many missing dependencies, I decided to look for other packages. 

There is the VSURF package which seems very promising, because it is completly writting in R and uses RandomForests which already works nicely. However, 5/6 tests are failing but, hopefully, due to an easy to fix problem:

org.renjin.gcc.runtime.DoublePtr to org.renjin.gcc.runtime.IntPtr 

What do you think?

Best,
Thorsten

**Comment by thorstenwagner** [comment]
Just for  your information:
varSelRF works perfectly with Renjin and is a good replacement of VSURF or the RF method from the caret package.

**Comment by akbertram** [comment]
Good to hear! This is the same problem as #276 so I will close this issue as a duplicate.

**Comment by akbertram** [comment]
This has been resolved by #332. All VSURF examples are now passing: http://packages.renjin.org/package/org.renjin.cran/VSURF/1.0.3/build/18

(testthat does not complete within 30 seconds)
