### ISSUE TITLE
org.renjin.eval.EvalException: no internal function "readTableHead

### ISSUE THREAD

**Issue by adispennette** [bedatadriven/renjin#330]
The java code:

    RenjinScriptEngineFactory factory = new RenjinScriptEngineFactory();
    ScriptEngine engine = factory.getScriptEngine();
    engine.eval(new FileReader("/path/to/my/file.R"));

The R Code:

    fomat_decimal <- function(x, k) format(round(x, k), nsmall=k)

    mfm <- function(h, l, c) {
      return (((c - l) - (h - c)) / (h -l))
    }

    mfv <- function(vol, m) {
      return (m * vol)
    }

    calculate <- function(h, l, c, v) {
          adl <- 0.0;
          sourceFile <- "/path/to/file.csv"
          tbl <- read.table(sourceFile,header=FALSE,sep=",")
          rowCnt <- nrow(tbl)
          inputData <- tbl[1:8]
          result <- vector()
          for (c in 2:rowCnt) {
              dataRow <- inputData[c,1:8]
              h <- as.numeric(dataRow[2])
              l <- as.numeric(dataRow[3])
              c <- as.numeric(dataRow[4])
              v <- as.numeric(dataRow[6])
    
              multiplier <- mfm(h, l, c)
              value <- mfv(v, multiplier)
              adl = (adl + value)
              append(result, fomat_decimal(adl, 10))
          }
      return (result)
    }

    calculate()

**Comment by akbertram** [comment]
I dont have your csv  file, but I tested something similar on renjin-3.5-beta44 and it runs successfully.
