### ISSUE TITLE
Renjin sprintf floating point format specifier differs from R

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#351]
**Replicate**
1. Run `java -jar renjin-studio-0.8.2507-jar-with-dependencies.jar`
1. Type:  `sprintf( '%0.f', 3 )`

**Expected Results**
```
[1] "3"
```

**Actual Results**
```
[1] "3.000000"
```

**Work Around**
```
printf( '%0.0f', 3 )
```

**Comment by akbertram** [comment]
Fixed in 0.8.2508
