### ISSUE TITLE
gsub() returns incorrect result if pattern matches zero-length strings

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#354]
**Replicate**
``` .R
gsub( '^0*', '', '123' )
```

**Expected Results**
```
[1] "123"
```

**Actual Results**
```
[1] "23"
```

**Work Around**
``` .R
gsub( '^0*', '', paste0( '0', '123' ) )
```

**Additional Details**
* Renjin 0.8.2508
* Linux hostname 4.8.4-040804-generic #201610220733 SMP Sat Oct 22 11:35:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* java version "1.8.0_121"

**Comment by akbertram** [comment]
Another workaround is to use a pattern that does not match zero-length strings, for example: 

    gsub( '^0+', '', '123')

This works fine.
