### ISSUE TITLE
S4 dispatch does not consider super-classes of primitive classes

### ISSUE THREAD

**Issue by chuanwen** [bedatadriven/renjin#355]
```
> library(glmnet)
> x = matrix(rnorm(3000), ncol=3)
> y = rnorm(1000)
> fit = glmnet(x, y)
> fit
> fit = cv.glmnet(x, y)
ERROR: invalid or not-yet-implemented 'Matrix' subsetting
  at stop()
  at function(x=<missing_arg>, i=<missing_arg>, j=<missing_arg>, ...=<missing_arg>, drop=TRUE)()
  at nrow()
  at nonzeroCoef()
  at predict.glmnet()
  at NextMethod()
  at predict.elnet()
  at predict()
  at is.vector()
  at lapply()
  at sapply()
  at cv.glmnet()
```

**Comment by akbertram** [comment]
This is actually in the `Matrix` package, and appears to be an issue with S4 dispatch.

The following is the minimal reproducible example:

```.R
m <- Matrix(c(0,0,2:0), 3,5)
m <- m[1, 1]
```
According to `selectMethod()`, this should resolve to:

```
> selectMethod("[", signature=c("dgCMatrix", "integer", "missing" , "missing"))
Signatures:
        x           i         j         drop     
target  "dgCMatrix" "integer" "missing" "missing"
defined "Matrix"    "index"   "missing" "missing"
```

Whereas Renjin dispatches to: 

```.R
setMethod("[", signature(x = "Matrix", i = "ANY", j = "ANY", drop = "ANY"),
	  function(x,i,j, ..., drop)
	  stop("invalid or not-yet-implemented 'Matrix' subsetting"))
```

This `index` class looks suspicious to me. According to `getClass()`, it is a superclass of `integer` and `numeric`:

```
> getClass("index")
Extended class definition ( "ClassUnionRepresentation" )
Virtual Class "index" [package "Matrix"]

No Slots, prototype of class "numeric"

Known Subclasses: 
Class "numeric", directly
Class "logical", directly
Class "character", directly
Class "integer", by class "numeric", distance 2
Class "signature", by class "character", distance 2
Class "className", by class "character", distance 2
Class "ObjectsWithPackage", by class "character", distance 2
Class "factor", by class "numeric", distance 3
```

But `inherits(9, "index")` evaluates to `FALSE`. 

So do we need special handling for super-classes of built-in classes @psolaimani ?

**Comment by psolaimani** [comment]
For signature generation, the classes of input arguments are computed. when [calling](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/primitives/S3.java#L923) `computeDataClasses()` on the provided `1.0` argument, classes `double` and `numeric` are returned. This is of course expected and correct. To get the `index` class, however, something like `extends('numeric')` needs to be used. This is not what is happening in all other cases of S4 signature generation.

**Comment by psolaimani** [comment]
this issue is solved [here](https://github.com/bedatadriven/renjin/commit/726a5433fab204080436eb1d94969f6ba0170808)
