### ISSUE TITLE
patched netlib does not use vecLib on Mac OS X

### ISSUE THREAD

**Issue by onedigit** [bedatadriven/renjin#37]
In order to use the current netlib java release 1.1.1 (and vecLib on Mac OS X), I had to modify a few files in renjin and rebuild.  The changes are as follows:

modify 
```
./core/pom.xml 
./appl/pom.xml 
```
and replace the netlib dependency with:
```
<dependency>
    <groupId>com.github.fommil.netlib</groupId>
    <artifactId>all</artifactId>
    <version>1.1.1</version>
    <type>pom</type>
 </dependency>
```

Then I had to fix the package imports on the following Java source files:

```
core/src/main/java/org/renjin/primitives/matrix/MatrixProduct.java
core/src/main/java/org/renjin/base/Lapack.java
appl/src/main/java/org/renjin/appl/ExternalRoutines.java
````
The new imports are (instead of org.netlib.blas.BLAS):
```
import com.github.fommil.netlib.BLAS
import com.github.fommil.netlib.LAPACK
```

**Comment by akbertram** [comment]
This has  been fixed in 29b42392e60b40e3632c9bc0752fa721420058be
