### ISSUE TITLE
Package read.dbc depends on dbc2dbf

### ISSUE THREAD

**Issue by tioback** [bedatadriven/renjin#386]
I was trying to use [read.dbc](http://packages.renjin.org/package/org.renjin.cran/read.dbc) in my project, however I got the following error:

    Exception in thread "main" org.renjin.eval.EvalException: Could not resolve native method 'dbc2dbf'

It seems to me that the packages aren't linked. I've searched ```dbc2dbf``` in both Renjin's repositories, but couldn't find it.

**Comment by akbertram** [comment]
`dbc2dbf` is apparently a function written in C, part of the read.dbc package:
https://github.com/cran/read.dbc/blob/1.0.5/src/dbc2dbf.c

Normally, Renjin's tool chain would compile this C code to JVM bytecode, but in the case of this package, that step failed:
http://packages.renjin.org/package/org.renjin.cran/read.dbc/1.0.5/build/24

The compiler seems to fail on a handling a global variable. There are also a few warnings about I/O functions from the standard library.

**Comment by tioback** [comment]
Thanks for the quick reply, @akbertram .

I tried using build [14](http://packages.renjin.org/package/org.renjin.cran/read.dbc/1.0.5/build/14), which was supposedly OK. However, I ended up with the same error as the build log shows:

    Caused by:java.lang.UnsupportedOperationException: fopen() not implemented

Curiously build 14 shows as SUCCESS, even though the log shows the errors.

I suck at C and R, would you guess it is a problem with the package or renjin itself?

**Comment by akbertram** [comment]
It was definitely Renjin's compiler, though I've fixed that now.

The package now completes building, which is why you see the "SUCCESS" message, but there are still a number of things incomplete in our emulation of the C Stdlib I/O routines. I'll try to plug away at it over the coming week.

**Comment by akbertram** [comment]
Actually, they seem to have been quick fixes. All tests are now passing in the read.dbc package:
http://packages.renjin.org/package/org.renjin.cran/read.dbc/1.0.5/build/30

**Comment by tioback** [comment]
Thanks a lot, @akbertram - I've just tested it and everything is working smoothly, now.

Cheers, man!
