### ISSUE TITLE
Function 'd1mach_' was not found at compile-time

### ISSUE THREAD

**Issue by mikewin** [bedatadriven/renjin#389]
Run example code is ok, but when try  loess,  return error

code :
df <- data.frame(x=1:10, y=(1:10)+rnorm(n=10))
lm(y ~ x, df)  
loess(y ~ x, df)

Function 'd1mach_' was not found at compile-time

(version: 0.9.2613)

**Comment by akbertram** [comment]
This has since been fixed -- I have just tested with 0.9.2660 and the code above works correctly.

**Comment by akbertram** [comment]
Sorry, actually I see a similar error in the latest build of the forecast package:
http://packages.renjin.org/package/org.renjin.cran/forecast/8.4/build/6#test-forecast.baggedModel-examples
