### ISSUE TITLE
gcc-bridge weird transformation

### ISSUE THREAD

**Issue by nicolas-f** [bedatadriven/renjin#392]
Hi,

After a long and tedious search in the source code I found a strange transformation in gcc-bridge. There's a problem, isn't there?

```c
void func( ) {
	uint16_t element = 1;
	uint16_t i;
	for (i = 1; i < 512; i++) {
		element = element * 2;
	}
}
```

transformed to

```java
   void func( ) {
    char element = (char)1;
    for(char i = (char)1; i <= (char)511; i += (char)1) {
      element += (char)2;
    }
   }
```

There is no typo here. The transformed operator is + instead of *

**Comment by nicolas-f** [comment]
gimple say mult_expr. so its recognized

```json
            {
              "type": "assign",
              "line": 50,
              "file": "/media/sf_github/openwarble/libcorrect/include/correct/reed-solomon/field.h",
              "operator": "mult_expr",
              "lhs": {
                "code": "var_decl",
                "type": {
                  "type": "integer_type",
                  "size": 16,
                  "unsigned": true
                },
                "id": -2393,
                "name": "element"
              },
              "operands": [
                {
                  "code": "var_decl",
                  "type": {
                    "type": "integer_type",
                    "size": 16,
                    "unsigned": true
                  },
                  "id": -2393,
                  "name": "element"
                },
                {
                  "code": "integer_cst",
                  "type": {
                    "type": "integer_type",
                    "size": 16,
                    "unsigned": true
                  },
                  "value": 2,
                  "type": {
                    "type": "integer_type",
                    "size": 16,
                    "unsigned": true
                  }
                }
              ]
            }
```

**Comment by akbertram** [comment]
I'm afraid it's a typo :$
https://github.com/bedatadriven/renjin/blob/87f1babc70b37dc6fbcb166232eb9aad36cf3c98/tools/gcc-bridge/compiler/src/main/java/org/renjin/gcc/codegen/type/primitive/UnsignedSmallIntExpr.java#L74

**Comment by nicolas-f** [comment]
Nice you found a fix. Thanks!

**Comment by nicolas-f** [comment]
The build 0.9.2614 have failed on your jenkins instance.


Failed to transfer file: https://nexus.bedatadriven.com/content/repositories/renjin-release/org/renjin/parent/0.9.2614/parent-0.9.2614.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by nicolas-f** [comment]
Nice thanks you its fixed now.

**Comment by akbertram** [comment]
Great! Thanks for tracking down the bug!

**Comment by nicolas-f** [comment]
Nope, IntelliJ decompiler is pure magic.

**Comment by nicolas-f** [comment]
This is for a reed solomon code (forward error correction)

**Comment by akbertram** [comment]
This probably explains the failure that cropped up in R's digest package...

**Comment by nicolas-f** [comment]
It works perfectly now. Your library should be much more widely used. Not having to rewrite Java from C is a huge time saving.
