### ISSUE TITLE
gcc-bridge Android

### ISSUE THREAD

**Issue by nicolas-f** [bedatadriven/renjin#393]
Hi,

This is more a notification than an issue.

I've successfully deployed [a library](https://github.com/nicolas-f/openwarble) on Android converted from C to Java thanks to renjin. However as gcc-bridge is using Java 8 it works only on Android starting from Android Oreo (ex: Integer.compareUnsigned)

I've started to make change on a fork in order to be compatible with Android Api level 15 (ICE_CREAM_SANDWICH)

**Comment by akbertram** [comment]
That's pretty cool!
I've only recently migrated to these Java 8 APIs, see for example: 784cce89c2df01c112a3a11fa2e330a1c385c410. Perhaps you could add a simple flag to configure the API level? We don't really push down any global configuration/context down to the level of `UnsignedIntExpr`, but you could easily wire up a simple system property.

The compiler also uses MethodHandles extensively for function pointers, but I think nothing above Java 1.7. I'm not sure what the support for this is on Android, or if your code uses function pointers at all.

**Comment by nicolas-f** [comment]
Thanks for pointing out the interesting commit.

I don't think libcorrect use function pointer.
