### ISSUE TITLE
ScriptEngine is not serializable!!

### ISSUE THREAD

**Issue by miguelangelmesas** [bedatadriven/renjin#395]
Hi all there!.  I am trying to use Renjin in a Storm project, but the cluster doesn't work because I use the engine as a member of a class (Bolt).

This is the error log:
9416 [main] ERROR o.a.s.s.o.a.z.s.NIOServerCnxnFactory - Thread Thread[main,5,main] died
java.lang.RuntimeException: **java.io.NotSerializableException: org.renjin.script.RenjinScriptEngine**
	at backtype.storm.utils.Utils.javaSerialize(Utils.java:91) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.topology.TopologyBuilder.createTopology(TopologyBuilder.java:107)

I tried 
private org.renjin.script.RenjinScriptEngine  engine; //ScriptEngine
instead
private ScriptEngine engine; _but the result is the same._

The unique solution I found is:
transient private ScriptEngine engine;

I use engine as a member os the Bolt class because I need the engine like a session of R work, different values as long the time of execution.

Any Idea for not use transient? 
Thanks in advance.
Miguel

**Comment by akbertram** [comment]
See response here: https://groups.google.com/forum/#!topic/renjin-dev/aXpnFMGEsVw

**Comment by miguelangelmesas** [comment]
Thanks for your comments
