### ISSUE TITLE
IS_CACHED() function missing

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#397]
We have a number of regressions in model-related code because of a missing GNU R API function called "IS_CACHED":

http://packages.renjin.org/qa/testRegression/org.renjin.cran/luca/1.0-5/summary_luca-examples#broken

**Comment by psolaimani** [comment]
resolved [here](https://github.com/bedatadriven/renjin/commit/f26d48c0380a236d9beaeb51eddc448890156297)
