### ISSUE TITLE
Cannot load dynamic R lib using AetherPackageLoader

### ISSUE THREAD

**Issue by yannrichet** [bedatadriven/renjin#400]
Hi, 

Maybe 'm doing something wrong, but I expected such code would work:

`
import org.junit.Before;
import org.junit.Test;
import org.renjin.aether.AetherPackageLoader;
import org.renjin.eval.Session;
import org.renjin.eval.SessionBuilder;
import org.renjin.primitives.packaging.PackageLoader;
import org.renjin.script.RenjinScriptEngine;
import org.renjin.script.RenjinScriptEngineFactory;

public class RenjinLibraryTest {

    RenjinScriptEngine R = null;

    public static void main(String args[]) {
        org.junit.runner.JUnitCore.main(RenjinLibraryTest.class.getName());
    }

    @Test
    public void testInstallPackage() throws Exception {
        R.eval("library('pso')");
    }

    @Before
    public void setUp() throws Exception {
        Session session = new SessionBuilder().bind(PackageLoader.class, new AetherPackageLoader()).build();
        R = new RenjinScriptEngineFactory().getScriptEngine(session);
        if (R == null) {
            throw new RuntimeException("Renjin Script Engine not found in the classpath.");
        }
    }
}
` 

Instead, returns java.lang.AbstractMethodError: org.renjin.aether.AetherPackageLoader.load(Lorg/renjin/primitives/packaging/FqPackageName;)Ljava/util/Optional;

I just loaded these deps in maven for this project (I don't want to explicitly load each R lib):
`
        <dependency>
            <groupId>org.renjin</groupId>
            <artifactId>renjin-script-engine</artifactId>
            <version>0.9.2620</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-api</artifactId>
            <version>1.0.2.v20150114</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.renjin</groupId>
            <artifactId>renjin-aether-package-loader</artifactId>
            <version>0.8.1938</version>
            <type>jar</type>
        </dependency>
`

Best,

Yann

**Comment by akbertram** [comment]
Dear Yann,

It looks like you are using an older version of
renjin-aether-package-loader (0.8.1938) with a new version of
renjin-script-engine (0.9.2620). Both dependencies should use the same
version, for example 0.9.2620.

Best,
Alex

**Comment by akbertram** [comment]
It looks like you are using an older version of renjin-aether-package-loader (0.8.1938) with a new version of renjin-script-engine (0.9.2620). Both dependencies should use the same version, for example 0.9.2620.
