### ISSUE TITLE
Github releases and changlog.md?

### ISSUE THREAD

**Issue by holgerbrandl** [bedatadriven/renjin#401]
Maybe I'm just missing it, but is there some changlog? The gh releases don't seem to reflect the current development as well.

**Comment by akbertram** [comment]
I've synced the GitHub releases page with our release history... does that help? We follow a pretty continous development process, so each merge/commit to master goes through the pipeline and is deployed as a release if everything passes.

We also have a dashboard tracking package compatibility here:
http://packages.renjin.org/qa/dashboard

You should consider this "eventually consistent" :-)
It takes some time to review test regressions and weed out the false positives.

**Comment by holgerbrandl** [comment]
Thanks.
