### ISSUE TITLE
javadocs for download

### ISSUE THREAD

**Issue by zcaudate** [bedatadriven/renjin#404]
would it be possible to create a zip of the javadocs for offline browsing? I tried to generate the javadocs from source but ran into some issues.

**Comment by zcaudate** [comment]
A single archive would be great. I'm using dash for offline documentation viewing so am looking to generate rejin for that.

**Comment by zcaudate** [comment]
just curious. how does graalvm compare with renjin?

**Comment by Alain-Bearez** [comment]
> just curious. how does graalvm compare with renjin?

While GraalVM resolved the issue of 
```
Exception calling Calloccolwrapper : Unimplemented GNU R API function 'SETLENGTH'
```
which I was not able to fix in Renjin, they still have the issue of
```
An internal error occurred: "not implemented: .Internal rapply"
```
which I was able to fix in Renjin.

But this is definitely not the right place for such a conversation...

**Comment by zcaudate** [comment]
Is there any progress on this? I'm hoping to be able to use this in https://kapeli.com/dash and not being able to download/generate javadocs kinda sucks.
