### ISSUE TITLE
Consider exporting `NO_GNUR` when compiling R packages

### ISSUE THREAD

**Issue by steve-s** [bedatadriven/renjin#409]
Hello, 

in FastR we started exporting macro `NO_GNUR` when compiling packages so that there is a way to detect an alternative engine [1]. We've done this after we got asked by Lionel (rlang maintainer) if there is any way to detect an alternative R engine (https://github.com/r-lib/rlang/issues/623) and we thought other alternative R engines could follow this too.
[1] https://github.com/oracle/fastr/commit/8403c6df0234b5260e95ea379ae51a8f54e63295

**Comment by akbertram** [comment]
As discussed at UseR!, I'm not sure what package authors would do with this information. There might be things that need to be adapted for Renjin, but I'm not sure they would be the same things that need to be adapted for FastR.

We do export the "RENJIN" cpp symbol.
