### ISSUE TITLE
default repos not public

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#430]
In the docs on http://docs.renjin.org/en/latest/library/execution-context.html
There is an example to use the AetherPackageLoader

However, the following lines does not compile as the renjinRepo and mavenCentral methods are not public

repositories.add(AetherFactory.renjinRepo());
repositories.add(AetherFactory.mavenCentral());

Please make them public!

**Comment by akbertram** [comment]
New build on its way...

**Comment by akbertram** [comment]
0.9.2716 Released
