### ISSUE TITLE
Data.frame rounds numeric to 3 decimals

### ISSUE THREAD

**Issue by Amglnbtr** [bedatadriven/renjin#436]
Hi. Creating data frame within renjin results all numeric to be rounded to 3 decimals.

```
> df <- data.frame('a'=0.123456, 'b'=0.321654)
> df
  a     b    
1 0.123 0.322
```

Creating list is ok

```
> df <- list('a'=0.123456, 'b'=0.321654)
> df
$a
[1] 0.123456

$b
[1] 0.321654
```
GNU R of course doesn't do this. Is this intentional? or what is my problem?
Update: Seems like its only showing first 3 digits, but stored value has 6 digits.
```
> sprintf("%.10f",df$a)
[1] "0.1234560000"
```
Is there any option to set it to higher value? I am using Renjin Studio, the jar file.

**Comment by strboul** [comment]
This issue is just about the behavior of S3 `print.data.frame()` method in renjin. You can still obtain the exact numeric values in the data frame by indexing it e.g. `df$a` or `df$b`. 

Therefore, this kind of printing method, which I believe this is the default one for data frames in renjin, can be also achieved in GNU R with e.g. `print(df, digits = 3)`. Saying again that is only about how the data frame is printed to the console and no worries about the correctness of the actual calculation.

**Comment by Amglnbtr** [comment]
> This issue is just about the behavior of S3 `print.data.frame()` method in renjin. You can still obtain the exact numeric values in the data frame by indexing it e.g. `df$a` or `df$b`.
> 
> Therefore, this kind of printing method, which I believe this is the default one for data frames in renjin, can be also achieved in GNU R with e.g. `print(df, digits = 3)`. Saying again that is only about how the data frame is printed to the console and no worries about the correctness of the actual calculation.

I was curious if there is a way to set it to higher digits in Renjin. But its not that important. Thanks anyway.

**Comment by Amglnbtr** [comment]
> This issue is just about the behavior of S3 `print.data.frame()` method in renjin. You can still obtain the exact numeric values in the data frame by indexing it e.g. `df$a` or `df$b`.
> 
> Therefore, this kind of printing method, which I believe this is the default one for data frames in renjin, can be also achieved in GNU R with e.g. `print(df, digits = 3)`. Saying again that is only about how the data frame is printed to the console and no worries about the correctness of the actual calculation.

I was curious if there is a way to set it to higher digits in Renjin. But its not that important. Thanks anyway.
