### ISSUE TITLE
Different output from GNU R for .Platform$OS.type and Sys.info()

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#439]
Sometimes you need to know the OS to be able to write scripts than can run on any platform (e.g. to use windows or unix path format). There is a difference between output from Renjin 0.9.2717 and GNU R 3.5.2 on Windows.

**On Windows 10**
```
_Gnu R_
> print(.Platform$OS.type)
[1] "windows"
> print(Sys.info()["sysname"])
  sysname 
"Windows" 
```
_Renjin_
```
> print(.Platform$OS.type)
[1] "unix"
> print(Sys.info()["sysname"])
sysname     
"Windows 10"
```
Here .Platform$OS.type is not correct - it should not report unix on a Windows OS.

**On Linux Mint 19.1**
```
_Gnu R_
> print(.Platform$OS.type)
[1] "unix"
> print(Sys.info()["sysname"])
sysname 
"Linux" 
```

_Renjin_
```
> print(.Platform$OS.type)
[1] "unix"
print(Sys.info()["sysname"])
sysname
"Linux"
```
I.e. behavior on Linux is identical to GNU R.

If GNU R should be the reference standard then we should change output - if not then i think we should document the different behavior.

**Comment by akbertram** [comment]
Have tried to fix. Can you verify on a windows machine?

**Comment by perNyfelt** [comment]
Verified on Windows 10 and Renjin 3.5-beta49: Sys.info()["sysname"] now gives the same output as GNU R. 
Thanks!

**Comment by perNyfelt** [comment]
Btw. Sys.info()["sysname"] still gives different output ("Windows 10" vs "Windows") but i don't think this is an issue (and i like what Renjin does more).
