### ISSUE TITLE
Implement greaterThan and lessThan for hamcrest tests

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#441]
When writing hamcrest tests i miss the matchers greaterThan and lessThan.

A simple start would be 
greaterThan <- function(expected) {
	function(actual) {
		actual > expected
  	}
}

lessThan <- function(expected) {
	function(actual) {
		actual < expected
  	}
}

But i am not sure how those should work for vectors i.e. if 
greaterThan <- function(expected) {
	function(actual) {
		all(actual > expected)
  	}
}
is what is meant by greaterThan in this case or if the vector size should be the determining factor; but I guess it should be treated the same as the closeTo matcher.

**Comment by akbertram** [comment]
I'm not sure if you want to duplicate the logic of closeTo() here... if you needed the logic than you could write a matcher like:

```.R
assertThat(x, either(closeTo(0), greaterThan(0))
```
What the `greaterThan` and `lessThan` matchers _do_ need to take into account is non finite values and NAs.

**Comment by perNyfelt** [comment]
Something like this perhaps:

greaterThan <- function(expected) {
    if(is.na(expected)) {
        stop("expected is NA, greaterThan NA makes no sense")
        expected <- na.omit(expected)
    }
    if (any( sapply(expected, is.infinite))) {
        stop("expected is infinite, greaterThan infinite makes no sense")
    }
    function(actual) {
        all(actual > expected)
    }
}

lessThan <- function(expected) {
    if(is.na(expected)) {
        stop("expected is NA, lessThan NA makes no sense")
        expected <- na.omit(expected)
    }
    if (any( sapply(expected, is.infinite))) {
        stop("expected is infinite, lessThan infinite makes no sense")
    }
    function(actual) {
        all(actual < expected)
    }
}

Test cases:
test.greaterThanNormal <- function() {
    assertThat(23, greaterThan(22))
}

test.greaterThanNa <- function() {
    res <- tryCatch(error = function(cnd) cnd, assertThat(2, greaterThan(NA)))
    hasErrMsg <- grepl("expected is NA, greaterThan NA makes no sense", res$message, fixed=TRUE)
    assertTrue(hasErrMsg)
}

test.greaterThanInf <- function() {
    res <- tryCatch(error = function(cnd) cnd, assertThat(34, greaterThan(20/0)))
    hasErrMsg <- grepl("expected is infinite, greaterThan infinite makes no sense", res$message, fixed=TRUE)
    assertTrue(hasErrMsg)
}

test.lessThanNormal <- function() {
    assertThat(20, lessThan(22))
}

test.lessThanNa <- function() {
    res <- tryCatch(error = function(cnd) cnd, assertThat(2, lessThan(NA)))
    hasErrMsg <- grepl("expected is NA, lessThan NA makes no sense", res$message, fixed=TRUE)
    assertTrue(hasErrMsg)
}

test.lessThanInf <- function() {
    res <- tryCatch(error = function(cnd) cnd, assertThat(34, lessThan(20/0)))
    hasErrMsg <- grepl("expected is infinite, lessThan infinite makes no sense", res$message, fixed=TRUE)
    assertTrue(hasErrMsg)
}

**Comment by mjkallen** [comment]
Wouldn't you do something like
```r
assertTrue(all(x > y)) # all() has na.rm = FALSE as default
```

Note also that we are preparing the _hamcrest_ package for release to CRAN in a branch at https://github.com/bedatadriven/hamcrest/tree/overhaul-hamcrest.

**Comment by perNyfelt** [comment]
Yes I think that would work.

As greaterThan and lessThan matchers exists for java hamcrest (http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#greaterThan(T)) it would make sense to support.

Nice to see the overhaul. I'll see if I can contribute with some tests.
