### ISSUE TITLE
RPostgreSQL is broken

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#444]
It seems that the RPostgreSQL package is broken in the latest release (even though the package listing indicates that it is fine: http://packages.renjin.org/package/org.renjin.cran/RPostgreSQL):

Renjin 0.9.2719
Copyright (C) 2019 The R Foundation for Statistical Computing
Copyright (C) 2019 BeDataDriven
> library(RPostgreSQL)
Loading required package: methods
Loading required package: DBI
Loading required package: methods
Warning messages:
1: Could not load compiled Fortran/C/C++ sources class for package org.renjin.cran:RPostgreSQL.
This is most likely because Renjin's compiler is not yet able to handle the sources for this
particular package. As a result, some functions may not work.

2: Could not load the dynamic library: org.renjin.cran.RPostgreSQL.RPostgreSQL

**Comment by akbertram** [comment]
The work you've done on RPostgresSQL is published, and loading the library via the command line will load the replacement version, not the version that relies on the native library:

http://packages.renjin.org/package/org.renjin.cran/RPostgreSQL
