### ISSUE TITLE
Add support for numeric and timestamp to RJDBC

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#446]
I suggest a simple change to the classes DateStringColumnBuilder (add support for the timestamp type) and DoubleColumnBuilder (add support for the numeric type) to RJDBC.

There is not "issue" feature on the renjin-dbi project so hopefully the right thing to do is to open it here instead.

Using RJDBC on PostgreSQL i get an error when reading from a table containing a column of type numeric(18,2) as follows:

R code was:
```
library('org.renjin.cran:RJDBC')
library(DBI)

drv <- JDBC("org.postgresql.Driver")
con <- dbConnect(drv,
url="jdbc:postgresql://localhost:5432/rsg", user="xxx", password="xxx")

projectInfoId <- 218
components <- dbGetQuery(con, paste("select * from component where project_id = ", projectInfoId))

```
Looking at the "caused by" part of the stacktrace it seems that JDBCUtils is used to map values.
Caused by: org.renjin.eval.EvalException: Unknown column type list(name = current_loan_amount, type = numeric)
at org.renjin.cran.DBI.JDBCUtils.fetch(JDBCUtils.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.renjin.invoke.reflection.FunctionBinding$Overload.invoke(FunctionBinding.java:117)

I have seen this issue on both Postgres and SQL server.

To fix the issue, add numeric to the double type i.e: in org.renjin.cran.DBI.columns.DoubleColumnBinder change the method acceptsType to include numeric as follows:

```
public static boolean acceptsType(String columnType) {
  return columnType.equals("decimal") || columnType.equals("real") || columnType.equals("number") 
	|| columnType.equals("numeric") || columnType.startsWith("double") || columnType.startsWith("float");
}
```

also in the org.renjin.cran.DBI.columns.DateStringColumnBuilder add support for the timestamp data type:

```
    public static boolean acceptsType(String columnType) {
        return columnType.equals("datetime") || columnType.equals("timestamp");
    }
```

The code can be seen in https://github.com/perNyfelt/renjin-dbi/tree/master/RJDBC/src/main/java/org/renjin/cran/DBI/columns

there is also a hamcrest test here: https://github.com/perNyfelt/renjin-dbi/blob/master/RJDBC/src/test/R/TestH2.R Which might be nice to add. A h2 test dependency needs to be added to the pom for the test to work i.e:

```
	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
		<version>1.4.197</version>
		<scope>test</scope>
	</dependency>
```
As I could not quite the the renjin plugin to work on windows, so I used my own hamcrest test plugin to verify the test, I cannot create a pull request but hope that this should be helpful anyway.

**Comment by perNyfelt** [comment]
I have submitted a pull request for this (https://github.com/bedatadriven/renjin-dbi/pull/1)

**Comment by akbertram** [comment]
Accepted! Many thanks!
