### ISSUE TITLE
shapiro.test not working: C_swilk missing?

### ISSUE THREAD

**Issue by tfeseker** [bedatadriven/renjin#462]
Hi,

I would like to test the normality of a set of values using the shapiro.test() function in the renjin library. The base R function is implemented, but it relies on the C call to C_swilk, which appears to be missing.

ListVector shapiro = (ListVector)engine.eval("shapiro.test(runif(100))");

results in

org.renjin.eval.EvalException: object 'C_swilk' not found

Same thing happens when I try it in renjin studio:

> shapiro.test(runif(100))
Error: object 'C_swilk' not found

Any help on how to solve this issue would be greatly appreciated!

Tom

**Comment by akbertram** [comment]
This is fixed in renjin-3.5-beta44
