### ISSUE TITLE
Implement missing `isFALSE()`

### ISSUE THREAD

**Issue by strboul** [bedatadriven/renjin#464]
The function `isFALSE()` is introduced to GNU R in version 3.5.0.

> New function isFALSE() defined analogously to isTRUE(). 

https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

**Comment by mjkallen** [comment]
Coming soon (see https://github.com/bedatadriven/renjin/commit/9e1c6b7aca1706af1df6c028b6133c0fcc3e809b).

**Comment by akbertram** [comment]
Fixed in renjin-3.5-beta44
