### ISSUE TITLE
No such internal 'det_ge_real'

### ISSUE THREAD

**Issue by MecBoc** [bedatadriven/renjin#496]
Hi,
I need to use the package SeleMix under Renjin, but I have this error:
No such internal 'det_ge_real'
and  this warning:
 WARNING: Failed to load implementation from: com.github.fommil.netlib.LAPACK

I followed the steps listed on  https://github.com/fommil/netlib-java , but it does not work yet.
Any suggestions?
Thanks in advance.

**Comment by MecBoc** [comment]
??

**Comment by akbertram** [comment]
We are missing this function in Renjin. You can find the GNU R implementation here:
https://github.com/wch/r-source/blob/fa2719c59ce56e0cfc2d0fd48f9fc196d7649241/src/modules/lapack/Lapack.c#L1260

It should be added to Lapack.java

Will be happy to review the pull request!

**Comment by francescoamato** [comment]
Hi,
the the function  'det_ge_real' is present in org.renjin.base.Lapack.java.
It works fine when I call it by JAVA  
     System.out.println(org.renjin.base.Lapack.det_ge_real(vec, true));  ==> OK
but I have the error  "No such internal 'det_ge_real'" when I call it in R script like  
    engine.eval("t<-.Internal(det_ge_real(y, TRUE))") ; ==> ERROR .
