### ISSUE TITLE
BeDataDriven Nexus repository is down

### ISSUE THREAD

**Issue by ctrueden** [bedatadriven/renjin#503]
The README says to use:
```
<repositories>
  <repository>
    <id>bedatadriven</id>
    <name>bedatadriven public repo</name>
    <url>https://nexus.bedatadriven.com/content/groups/public/</url>
  </repository>
</repositories>
```

But it seems the repository is down now:
```
$ curl -I https://nexus.bedatadriven.com/content/groups/public/
HTTP/2 404
content-type: text/html;charset=utf-8
x-cloud-trace-context: ada2be554237cc17b165ad738823260c
date: Mon, 04 May 2020 17:30:09 GMT
server: Google Frontend
content-length: 194
```

Is this downtime temporary? Or have the artifacts moved somewhere else?

**Comment by akbertram** [comment]
The artifacts are there, but directory listings are disabled. Is there an artifact you are missing?

**Comment by ctrueden** [comment]
@akbertram Ah, right, sorry for the false alarm. I just got concerned when my Nexus proxy of BeDataDriven reported that the repository had been auto-blocked. I turned off repository indexing and auto-blocking for BeDataDriven, then reenabled it; hopefully will be OK now!
