### ISSUE TITLE
Unable to integrate Rcpp package of renjin

### ISSUE THREAD

**Issue by atinjca** [bedatadriven/renjin#517]
I am trying to integrate r code in java and want to use cpp code in r code, but i am getting the following error.
It would be grateful if you can help me.

org.renjin.eval.EvalException: Could not resolve native method 'sourceCppContext' in package 'Rcpp' while running my java code.

My Java Code piece:
r.eval(String.format("source(\"" + appdir +  "/config/MyRscript.R\")"));

String rS = ((SEXP)r.eval("test("+i+")")).toString();

R code :
library(Rcpp)
sourceCpp("Rfunction.cpp")

test <- function(a) {
 
   x <<- timesTwo(a)
   print(x)
}

Cpp code :

#include <Rcpp.h>
using namespace Rcpp;
int timesTwo(int x) {
return x * 2;
}

**Comment by akbertram** [comment]
sourceCpp is definitely not supported by Renjin. You will need to move the c++ to a package, where it can be compiled at build time, or rewrite the code in R or Java.

**Comment by atinjca** [comment]
Thanks @akbertram
