### ISSUE TITLE
Renjin betadriven repository is down

### ISSUE THREAD

**Issue by david-bouyssie** [bedatadriven/renjin#521]
It seems that it is not possible to access the bedatadriven maven repository located at:
https://nexus.bedatadriven.com/content/repositories/public/

Is there any workaround?

**Comment by akbertram** [comment]
The repository is available, but directory listing is disabled.

**Comment by david-bouyssie** [comment]
Ok sorry, my mistake.

Directory listing is a convenient feature to check for a given package availability (and see which version is available), because sometimes mvnrepository.com is not indexing secondary repositories properly.
