### ISSUE TITLE
Implement Sys.which for Windows

### ISSUE THREAD

**Issue by david-bouyssie** [bedatadriven/renjin#522]
Sys.which() is not implemented for Windows:
https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/primitives/files/Files.java#L303

It seems there is a possible workaround which could be implemented using the Windows ```where``` command:
https://stackoverflow.com/questions/34030087/how-to-find-correct-executable-with-sys-which-on-windows
https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by akbertram** [comment]
I'm not sure why there's a check for Windows there, I believe the PATH environment variable is also present in Windows?

**Comment by david-bouyssie** [comment]
Actually there is one:

```
if(isWindows()) {
      throw new EvalException("Sys.which() not implemented for Windows");
    }
```

**Comment by david-bouyssie** [comment]
Yes, might be better to check PATH content first.

**Comment by david-bouyssie** [comment]
At least this is working a expected on my Windows system:

```Strings.nullToEmpty(System.getenv("PATH")).split(File.pathSeparator);```

So removing the check should be ok.

**Comment by perNyfelt** [comment]
I removed the windows check and verified that it is indeed working fine in windows: 
Renjin 3.5-dev
Copyright (C) 2019 The R Foundation for Statistical Computing
Copyright (C) 2021 BeDataDriven
Using native reference BLAS libraries.
> Sys.which("cmd.exe")
cmd.exe
"/C:/WINDOWS/system32/cmd.exe"

I will submit a PR...

**Comment by david-bouyssie** [comment]
👏 thanks
