### ISSUE TITLE
Cannot retrieve value because of deferred expression

### ISSUE THREAD

**Issue by mohateri** [bedatadriven/renjin#529]
Hello all,

I am using Renjin 3.5-beta43 in a Java project and I came across an inconvenience that I don't if it qualifies for a bug.
Here is my code:
```Java
RenjinScriptEngineFactory factory = new RenjinScriptEngineFactory();
ScriptEngine engine = factory.getScriptEngine();
engine.put("all", array_values);
engine.put("nb_values", nb_values);
engine.eval("mat <- matrix(all, nb_values)");
engine.eval("chi2 <- chisq.test(mat, correct=F)");
engine.eval("chi <- chi2$statistic[['X-squared']]");
engine.eval("rows <- dim(mat)[1]");
engine.eval("cols <- dim(mat)[2]");
engine.eval("total <- sum(mat)");
engine.eval("result <- sqrt((chi/total)/min(cols - 1, rows - 1))");
DoubleArrayVector resultArray = (DoubleArrayVector) engine.eval("result");
```
The thing is, I often get a `ClassCastException`, saying that I can't convert a `renjin$primitive$deferred` to a `DoubleArrayVector`.

Now I checked what is a deferred expression in Renjin, and I thought that adding a `engine.eval("print(result)");` before retrieving it would solve the problem. It would indeed not be a deferred expression then - or so I thought - because of the need to compute the expression to print it. But even though the printing was done, still the `ClassCastException` was thrown.

A solution I came across was finally this one:
```Java
StringWriter outputWriter = new StringWriter();
engine.getContext().setWriter(outputWriter);
engine.eval("print(result)");
String result = outputWriter.toString().split(" ")[1];
```
I just print the result into a StringWriter and get my result.

Is there a more elegant solution? Moreover, is this really a bug or is this working as intended?

**Comment by akbertram** [comment]
Why do you need specifically a DoubleArrayVector? In principle you should not assume that a vector in Renjin will be backed by an array, even if it is not deferred.

You should prefer the `DoubleVector` interface instead.
