### ISSUE TITLE
Is there a problem with the nexus.bedatadriven repo (for maven) ?

### ISSUE THREAD

**Issue by jeremyCarruba** [bedatadriven/renjin#530]
Hello there,
Hope it's the right spot to post,
A colleague developed a feature based on renjin and survival without any dependancy problem
But now that we try on an other terminal the repo seems unreachable ?
this one : 
        <repository>
            <id>bedatadriven</id>
            <name>bedatadriven public repo</name>
            <url>https://nexus.bedatadriven.com/content/groups/public/</url>
        </repository>

We found a mulesoft repo for renjin, but impossible to find anything for survival, which we need for logistic regression

        <repository>
            <id>renjin</id>
            <name>renjin</name>
            <url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
        </repository>

Can't seem to find a workaround, can we find survival somewhere else thant nexus.bedatadriven ?
Thank you in advance

**Comment by akbertram** [comment]
It should still be there, certainly. We have disabled directory listing though. have you checked whether the specific pom or jar is accessible?

**Comment by mzhang-github** [comment]
Same issue here, the pom and jar are not available, for example renjin-script-engine 3.5-beta76.

**Comment by yannrichet** [comment]
same for me.
but thx, anyway :)

**Comment by akbertram** [comment]
Alright, probably a config issue. I'll try to get it fixed this weekend

**Comment by akbertram** [comment]
This is now fixed, and I've added directory listings in https://github.com/bedatadriven/renjin-packages/commit/3a69d8354142542cdb2aa63854771ace0d180e64
