### ISSUE TITLE
Avoid writing double semicolon in SVG style attribute

### ISSUE THREAD

**Issue by ghost** [bedatadriven/renjin#555]
Not sure if this is a Renjin issue or a JFreeSVG issue.

When exporting a plot as SVG, a double semicolon is written. For example:

```r
svg("/tmp/filename.svg");
plot(rnorm(5));
dev.off();
```

Produces:

```
<ellipse
  cx="61.5" cy="219.5" rx="2.5" ry="2.5"
  style="...snip... stroke-linecap: square;; fill: none" ...snip... />
```

Unfortunately, the ConTeXt typesetting engine has a bug that ignores styles after a null entry is detected in the style list, resulting in all such diagrams being rendered as a big black square (because the `fill:none` isn't honoured).

Any idea what's causing the `;;` to be generated?

**Comment by akbertram** [comment]
Hi Dave, this is definitely in JFreeSVG, Renjin uses the Java Graphics2D API, for which JFreeSVG provides an implementation.
