### ISSUE TITLE
Linking with Renjin in non-GPL software

### ISSUE THREAD

**Issue by willplatt** [bedatadriven/renjin#562]
I'm looking to use Renjin as a library in my application, but the GPL requires that if I incorporate Renjin into my application (even though I don't modify it, just link with it) then my application also has to be licensed under GPL. This is a rather unfortunate barrier for my use of Renjin, and likely so for many others. As it says at the end of your current LICENSE.txt:

> This General Public License does not permit incorporating your program into
> proprietary programs.  If your program is a subroutine library, you may
> consider it more useful to permit linking proprietary applications with the
> library.  If this is what you want to do, use the GNU Library General
> Public License instead of this License.

Or you may simply add the [GPL linking/classpath exception](https://en.wikipedia.org/wiki/GPL_linking_exception) to your license. This would make Renjin more accessible for use in other libraries and applications, and I would greatly appreciate this myself. I really like Renjin and wouldn't want to miss out on using it in my work.

**Comment by akbertram** [comment]
Unfortunately as a project we don't have much control over this. Renjin is a derived work of the R Project for Statistical Computing, which is licensed under the GPL v2:
https://www.r-project.org/COPYING

I do not believe the terms of the GPL allows us to unilaterally add the classpath exception to a derived work when the original work does not include such an exception.

**Comment by willplatt** [comment]
I see. It seems unfortunate that R is licensed in such a way, as [it seems to be causing a lot of confusion and limiting its usefulness](https://r-posts.com/how-gpl-makes-me-leave-r-for-python/). Thanks for the explanation.
