### ISSUE TITLE
Unable to load Randomforest model

### ISSUE THREAD

**Issue by vvishwesh** [bedatadriven/renjin#567]
I created a randomForest model using R for the iris dataset and saved it in both .rds and .Rdata formats. 
The Java code used to load the model is below

engine.eval("library(randomForest)");
engine.eval("mdl = readRDS(\"rfmdl.rds\")"); 

Any ideas why I get the following error 
org.renjin.eval.EvalException: cannot read workspace version 3 written by R 3.5.0; need R 3.5.0 or newer

I created the model using R 4.3.1 on Windows.  I am trying the code taken from https://forum.image.sc/t/renjin-randomforest-and-fiji/5532

Help appreciated.

**Comment by perNyfelt** [comment]
Which version of Renjin and Java are you using? If i remember correctly, the latest Renjin 3.5 beta supports v3 rds files...

**Comment by vvishwesh** [comment]
I am using the latest Java version  "21.0.1" 2023-10-17 LTS
and Renjin  3.5-beta75

**Comment by perNyfelt** [comment]
OK i can reproduce the issue using the following steps:

> R
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
> saveRDS(iris, 'iris.rds')
> q()

> renjin
Renjin 3.5-beta76
> ir <- readRDS('iris.rds')
ERROR: cannot read workspace version 3 written by R 3.5.0; need R 3.5.0 or newer

However, saving as version 2 works. I.e:
`> saveRDS(iris, file='iris.rds', version=2)`
 Is that an option?

**Comment by vvishwesh** [comment]
The version=2, takes care of one problem but now I have another.  I continued as before with the following steps
       engine.eval("library(randomForest)");
       engine.eval("mdl = readRDS(\"iris.rds\")");
       engine.eval("print(mdl)");
       engine.eval("predict(mdl)");

The print step outputs model info but the next step of predict prints nothing nor does it raise an error.

**Comment by perNyfelt** [comment]
As far as i can tell predict behaves the same in Gnu R and Renjin:

GNU R
```R
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> model <- lm(dist~speed, data=cars)
> print model
Error: unexpected symbol in "print model"
> model

Call:
lm(formula = dist ~ speed, data = cars)

Coefficients:
(Intercept)        speed
    -17.579        3.932

> variable_speed <- data.frame(speed = c(11,11,12,12,12,12,13,13,13,13))
> prediction <- predict(model, newdata = variable_speed)
> print prediction
Error: unexpected symbol in "print prediction"
> prediction
       1        2        3        4        5        6        7        8
25.67740 25.67740 29.60981 29.60981 29.60981 29.60981 33.54222 33.54222
       9       10
33.54222 33.54222
>
```

Renjin
```R
Renjin 3.5-beta76
Copyright (C) 2019 The R Foundation for Statistical Computing
Copyright (C) 2019 BeDataDriven
Falling back to pure JVM BLAS libraries.
> model <- lm(dist~speed, data=cars)
> print model
Syntax error at 1 7 1 11 7 11: syntax error, unexpected SYMBOL, expecting '\n' or ';'
> model

Call:
lm(formula = dist ~ speed, data = cars)

Coefficients:
(Intercept) speed
-17.579       3.932

> variable_speed <- data.frame(speed = c(11,11,12,12,12,12,13,13,13,13))
> prediction <- predict(model, newdata = variable_speed)
> print prediction
Syntax error at 1 7 1 16 7 16: syntax error, unexpected SYMBOL, expecting '\n' or ';'
> prediction
[1] 25,67740145985406 25,67740145985406 29,60981021897814 29,60981021897814
[5] 29,60981021897814 29,60981021897814 33,54221897810223 33,54221897810223
[9] 33,54221897810223 33,54221897810223
>
```

**Comment by vvishwesh** [comment]
Sorry. Forgot to write "print" in my instruction

**Comment by perNyfelt** [comment]
Workaround acceptable.
